
namespace LibraryApp
{
    partial class AddBookScreen
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(AddBookScreen));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            this.topPanel = new System.Windows.Forms.Panel();
            this.exitButton = new Bunifu.UI.WinForms.BunifuImageButton();
            this.todayGetter = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.label1 = new System.Windows.Forms.Label();
            this.bunifuDragControl1 = new Bunifu.Framework.UI.BunifuDragControl(this.components);
            this.nameTaker = new Bunifu.UI.WinForms.BunifuTextBox();
            this.posTaker = new Bunifu.UI.WinForms.BunifuTextBox();
            this.publisherTaker = new Bunifu.UI.WinForms.BunifuTextBox();
            this.amountTaker = new Bunifu.UI.WinForms.BunifuTextBox();
            this.statusTaker = new Bunifu.UI.WinForms.BunifuTextBox();
            this.publishYearTaker = new Bunifu.UI.WinForms.BunifuTextBox();
            this.priceTaker = new Bunifu.UI.WinForms.BunifuTextBox();
            this.saveBt = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.authorSet = new Bunifu.UI.WinForms.BunifuDropdown();
            this.genreSet = new Bunifu.UI.WinForms.BunifuDropdown();
            this.topPanel.SuspendLayout();
            this.SuspendLayout();
            // 
            // topPanel
            // 
            this.topPanel.BackColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.topPanel.Controls.Add(this.exitButton);
            this.topPanel.Controls.Add(this.todayGetter);
            this.topPanel.Controls.Add(this.label1);
            this.topPanel.Dock = System.Windows.Forms.DockStyle.Top;
            this.topPanel.Location = new System.Drawing.Point(0, 0);
            this.topPanel.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.topPanel.Name = "topPanel";
            this.topPanel.Size = new System.Drawing.Size(941, 105);
            this.topPanel.TabIndex = 0;
            // 
            // exitButton
            // 
            this.exitButton.ActiveImage = null;
            this.exitButton.AllowAnimations = true;
            this.exitButton.AllowBuffering = false;
            this.exitButton.AllowToggling = false;
            this.exitButton.AllowZooming = true;
            this.exitButton.AllowZoomingOnFocus = false;
            this.exitButton.BackColor = System.Drawing.Color.Transparent;
            this.exitButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.exitButton.ErrorImage = ((System.Drawing.Image)(resources.GetObject("exitButton.ErrorImage")));
            this.exitButton.FadeWhenInactive = false;
            this.exitButton.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.exitButton.Image = global::LibraryApp.Properties.Resources.exit;
            this.exitButton.ImageActive = null;
            this.exitButton.ImageLocation = null;
            this.exitButton.ImageMargin = 5;
            this.exitButton.ImageSize = new System.Drawing.Size(39, 33);
            this.exitButton.ImageZoomSize = new System.Drawing.Size(44, 38);
            this.exitButton.InitialImage = ((System.Drawing.Image)(resources.GetObject("exitButton.InitialImage")));
            this.exitButton.Location = new System.Drawing.Point(883, 23);
            this.exitButton.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.exitButton.Name = "exitButton";
            this.exitButton.Rotation = 0;
            this.exitButton.ShowActiveImage = true;
            this.exitButton.ShowCursorChanges = true;
            this.exitButton.ShowImageBorders = true;
            this.exitButton.ShowSizeMarkers = false;
            this.exitButton.Size = new System.Drawing.Size(44, 38);
            this.exitButton.TabIndex = 2;
            this.exitButton.ToolTipText = "";
            this.exitButton.WaitOnLoad = false;
            this.exitButton.Zoom = 5;
            this.exitButton.ZoomSpeed = 10;
            this.exitButton.Click += new System.EventHandler(this.exitButton_Click);
            // 
            // todayGetter
            // 
            this.todayGetter.BackColor = System.Drawing.Color.White;
            this.todayGetter.BorderRadius = 1;
            this.todayGetter.Color = System.Drawing.Color.Silver;
            this.todayGetter.CustomFormat = "yyyy-MM-dd";
            this.todayGetter.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.todayGetter.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.todayGetter.DisabledColor = System.Drawing.Color.Gray;
            this.todayGetter.DisplayWeekNumbers = false;
            this.todayGetter.DPHeight = 0;
            this.todayGetter.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.todayGetter.FillDatePicker = false;
            this.todayGetter.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.todayGetter.ForeColor = System.Drawing.Color.Black;
            this.todayGetter.Icon = ((System.Drawing.Image)(resources.GetObject("todayGetter.Icon")));
            this.todayGetter.IconColor = System.Drawing.Color.Gray;
            this.todayGetter.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.todayGetter.LeftTextMargin = 5;
            this.todayGetter.Location = new System.Drawing.Point(13, 65);
            this.todayGetter.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.todayGetter.MinimumSize = new System.Drawing.Size(4, 32);
            this.todayGetter.Name = "todayGetter";
            this.todayGetter.Size = new System.Drawing.Size(345, 32);
            this.todayGetter.TabIndex = 6;
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label1.Location = new System.Drawing.Point(17, 32);
            this.label1.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(132, 29);
            this.label1.TabIndex = 0;
            this.label1.Text = "Thêm sách";
            // 
            // bunifuDragControl1
            // 
            this.bunifuDragControl1.Fixed = true;
            this.bunifuDragControl1.Horizontal = true;
            this.bunifuDragControl1.TargetControl = this.topPanel;
            this.bunifuDragControl1.Vertical = true;
            // 
            // nameTaker
            // 
            this.nameTaker.AcceptsReturn = false;
            this.nameTaker.AcceptsTab = false;
            this.nameTaker.AnimationSpeed = 200;
            this.nameTaker.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.nameTaker.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.nameTaker.BackColor = System.Drawing.Color.White;
            this.nameTaker.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("nameTaker.BackgroundImage")));
            this.nameTaker.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.nameTaker.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.nameTaker.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.nameTaker.BorderColorIdle = System.Drawing.Color.Silver;
            this.nameTaker.BorderRadius = 1;
            this.nameTaker.BorderThickness = 1;
            this.nameTaker.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.nameTaker.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.nameTaker.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.nameTaker.DefaultText = "";
            this.nameTaker.FillColor = System.Drawing.Color.White;
            this.nameTaker.HideSelection = true;
            this.nameTaker.IconLeft = null;
            this.nameTaker.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.nameTaker.IconPadding = 10;
            this.nameTaker.IconRight = null;
            this.nameTaker.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.nameTaker.Lines = new string[0];
            this.nameTaker.Location = new System.Drawing.Point(83, 149);
            this.nameTaker.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.nameTaker.MaxLength = 32767;
            this.nameTaker.MinimumSize = new System.Drawing.Size(1, 1);
            this.nameTaker.Modified = false;
            this.nameTaker.Multiline = false;
            this.nameTaker.Name = "nameTaker";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nameTaker.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.nameTaker.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nameTaker.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nameTaker.OnIdleState = stateProperties4;
            this.nameTaker.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.nameTaker.PasswordChar = '\0';
            this.nameTaker.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.nameTaker.PlaceholderText = "Tên sách";
            this.nameTaker.ReadOnly = false;
            this.nameTaker.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.nameTaker.SelectedText = "";
            this.nameTaker.SelectionLength = 0;
            this.nameTaker.SelectionStart = 0;
            this.nameTaker.ShortcutsEnabled = true;
            this.nameTaker.Size = new System.Drawing.Size(347, 46);
            this.nameTaker.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.nameTaker.TabIndex = 1;
            this.nameTaker.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.nameTaker.TextMarginBottom = 0;
            this.nameTaker.TextMarginLeft = 3;
            this.nameTaker.TextMarginTop = 0;
            this.nameTaker.TextPlaceholder = "Tên sách";
            this.nameTaker.UseSystemPasswordChar = false;
            this.nameTaker.WordWrap = true;
            // 
            // posTaker
            // 
            this.posTaker.AcceptsReturn = false;
            this.posTaker.AcceptsTab = false;
            this.posTaker.AnimationSpeed = 200;
            this.posTaker.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.posTaker.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.posTaker.BackColor = System.Drawing.Color.White;
            this.posTaker.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("posTaker.BackgroundImage")));
            this.posTaker.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.posTaker.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.posTaker.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.posTaker.BorderColorIdle = System.Drawing.Color.Silver;
            this.posTaker.BorderRadius = 1;
            this.posTaker.BorderThickness = 1;
            this.posTaker.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.posTaker.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.posTaker.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.posTaker.DefaultText = "";
            this.posTaker.FillColor = System.Drawing.Color.White;
            this.posTaker.HideSelection = true;
            this.posTaker.IconLeft = null;
            this.posTaker.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.posTaker.IconPadding = 10;
            this.posTaker.IconRight = null;
            this.posTaker.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.posTaker.Lines = new string[0];
            this.posTaker.Location = new System.Drawing.Point(519, 220);
            this.posTaker.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.posTaker.MaxLength = 32767;
            this.posTaker.MinimumSize = new System.Drawing.Size(1, 1);
            this.posTaker.Modified = false;
            this.posTaker.Multiline = false;
            this.posTaker.Name = "posTaker";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.posTaker.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.posTaker.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.posTaker.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.posTaker.OnIdleState = stateProperties8;
            this.posTaker.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.posTaker.PasswordChar = '\0';
            this.posTaker.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.posTaker.PlaceholderText = "Vị trí";
            this.posTaker.ReadOnly = false;
            this.posTaker.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.posTaker.SelectedText = "";
            this.posTaker.SelectionLength = 0;
            this.posTaker.SelectionStart = 0;
            this.posTaker.ShortcutsEnabled = true;
            this.posTaker.Size = new System.Drawing.Size(347, 46);
            this.posTaker.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.posTaker.TabIndex = 3;
            this.posTaker.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.posTaker.TextMarginBottom = 0;
            this.posTaker.TextMarginLeft = 3;
            this.posTaker.TextMarginTop = 0;
            this.posTaker.TextPlaceholder = "Vị trí";
            this.posTaker.UseSystemPasswordChar = false;
            this.posTaker.WordWrap = true;
            // 
            // publisherTaker
            // 
            this.publisherTaker.AcceptsReturn = false;
            this.publisherTaker.AcceptsTab = false;
            this.publisherTaker.AnimationSpeed = 200;
            this.publisherTaker.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.publisherTaker.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.publisherTaker.BackColor = System.Drawing.Color.White;
            this.publisherTaker.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("publisherTaker.BackgroundImage")));
            this.publisherTaker.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.publisherTaker.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.publisherTaker.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.publisherTaker.BorderColorIdle = System.Drawing.Color.Silver;
            this.publisherTaker.BorderRadius = 1;
            this.publisherTaker.BorderThickness = 1;
            this.publisherTaker.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.publisherTaker.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.publisherTaker.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.publisherTaker.DefaultText = "";
            this.publisherTaker.FillColor = System.Drawing.Color.White;
            this.publisherTaker.HideSelection = true;
            this.publisherTaker.IconLeft = null;
            this.publisherTaker.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.publisherTaker.IconPadding = 10;
            this.publisherTaker.IconRight = null;
            this.publisherTaker.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.publisherTaker.Lines = new string[0];
            this.publisherTaker.Location = new System.Drawing.Point(83, 220);
            this.publisherTaker.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.publisherTaker.MaxLength = 32767;
            this.publisherTaker.MinimumSize = new System.Drawing.Size(1, 1);
            this.publisherTaker.Modified = false;
            this.publisherTaker.Multiline = false;
            this.publisherTaker.Name = "publisherTaker";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.publisherTaker.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.publisherTaker.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.publisherTaker.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.publisherTaker.OnIdleState = stateProperties12;
            this.publisherTaker.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.publisherTaker.PasswordChar = '\0';
            this.publisherTaker.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.publisherTaker.PlaceholderText = "Nhà suất bản";
            this.publisherTaker.ReadOnly = false;
            this.publisherTaker.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.publisherTaker.SelectedText = "";
            this.publisherTaker.SelectionLength = 0;
            this.publisherTaker.SelectionStart = 0;
            this.publisherTaker.ShortcutsEnabled = true;
            this.publisherTaker.Size = new System.Drawing.Size(347, 46);
            this.publisherTaker.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.publisherTaker.TabIndex = 3;
            this.publisherTaker.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.publisherTaker.TextMarginBottom = 0;
            this.publisherTaker.TextMarginLeft = 3;
            this.publisherTaker.TextMarginTop = 0;
            this.publisherTaker.TextPlaceholder = "Nhà suất bản";
            this.publisherTaker.UseSystemPasswordChar = false;
            this.publisherTaker.WordWrap = true;
            // 
            // amountTaker
            // 
            this.amountTaker.AcceptsReturn = false;
            this.amountTaker.AcceptsTab = false;
            this.amountTaker.AnimationSpeed = 200;
            this.amountTaker.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.amountTaker.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.amountTaker.BackColor = System.Drawing.Color.White;
            this.amountTaker.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("amountTaker.BackgroundImage")));
            this.amountTaker.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.amountTaker.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.amountTaker.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.amountTaker.BorderColorIdle = System.Drawing.Color.Silver;
            this.amountTaker.BorderRadius = 1;
            this.amountTaker.BorderThickness = 1;
            this.amountTaker.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.amountTaker.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.amountTaker.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.amountTaker.DefaultText = "";
            this.amountTaker.FillColor = System.Drawing.Color.White;
            this.amountTaker.HideSelection = true;
            this.amountTaker.IconLeft = null;
            this.amountTaker.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.amountTaker.IconPadding = 10;
            this.amountTaker.IconRight = null;
            this.amountTaker.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.amountTaker.Lines = new string[0];
            this.amountTaker.Location = new System.Drawing.Point(519, 149);
            this.amountTaker.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.amountTaker.MaxLength = 32767;
            this.amountTaker.MinimumSize = new System.Drawing.Size(1, 1);
            this.amountTaker.Modified = false;
            this.amountTaker.Multiline = false;
            this.amountTaker.Name = "amountTaker";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.amountTaker.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.amountTaker.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.amountTaker.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.amountTaker.OnIdleState = stateProperties16;
            this.amountTaker.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.amountTaker.PasswordChar = '\0';
            this.amountTaker.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.amountTaker.PlaceholderText = "Số lượng";
            this.amountTaker.ReadOnly = false;
            this.amountTaker.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.amountTaker.SelectedText = "";
            this.amountTaker.SelectionLength = 0;
            this.amountTaker.SelectionStart = 0;
            this.amountTaker.ShortcutsEnabled = true;
            this.amountTaker.Size = new System.Drawing.Size(347, 46);
            this.amountTaker.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.amountTaker.TabIndex = 4;
            this.amountTaker.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.amountTaker.TextMarginBottom = 0;
            this.amountTaker.TextMarginLeft = 3;
            this.amountTaker.TextMarginTop = 0;
            this.amountTaker.TextPlaceholder = "Số lượng";
            this.amountTaker.UseSystemPasswordChar = false;
            this.amountTaker.WordWrap = true;
            // 
            // statusTaker
            // 
            this.statusTaker.AcceptsReturn = false;
            this.statusTaker.AcceptsTab = false;
            this.statusTaker.AnimationSpeed = 200;
            this.statusTaker.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.statusTaker.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.statusTaker.BackColor = System.Drawing.Color.White;
            this.statusTaker.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("statusTaker.BackgroundImage")));
            this.statusTaker.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.statusTaker.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.statusTaker.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.statusTaker.BorderColorIdle = System.Drawing.Color.Silver;
            this.statusTaker.BorderRadius = 1;
            this.statusTaker.BorderThickness = 1;
            this.statusTaker.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.statusTaker.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.statusTaker.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.statusTaker.DefaultText = "";
            this.statusTaker.FillColor = System.Drawing.Color.White;
            this.statusTaker.HideSelection = true;
            this.statusTaker.IconLeft = null;
            this.statusTaker.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.statusTaker.IconPadding = 10;
            this.statusTaker.IconRight = null;
            this.statusTaker.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.statusTaker.Lines = new string[0];
            this.statusTaker.Location = new System.Drawing.Point(83, 287);
            this.statusTaker.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.statusTaker.MaxLength = 32767;
            this.statusTaker.MinimumSize = new System.Drawing.Size(1, 1);
            this.statusTaker.Modified = false;
            this.statusTaker.Multiline = false;
            this.statusTaker.Name = "statusTaker";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.statusTaker.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.statusTaker.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.statusTaker.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.statusTaker.OnIdleState = stateProperties20;
            this.statusTaker.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.statusTaker.PasswordChar = '\0';
            this.statusTaker.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.statusTaker.PlaceholderText = "Trạng thái";
            this.statusTaker.ReadOnly = false;
            this.statusTaker.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.statusTaker.SelectedText = "";
            this.statusTaker.SelectionLength = 0;
            this.statusTaker.SelectionStart = 0;
            this.statusTaker.ShortcutsEnabled = true;
            this.statusTaker.Size = new System.Drawing.Size(347, 46);
            this.statusTaker.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.statusTaker.TabIndex = 4;
            this.statusTaker.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.statusTaker.TextMarginBottom = 0;
            this.statusTaker.TextMarginLeft = 3;
            this.statusTaker.TextMarginTop = 0;
            this.statusTaker.TextPlaceholder = "Trạng thái";
            this.statusTaker.UseSystemPasswordChar = false;
            this.statusTaker.WordWrap = true;
            // 
            // publishYearTaker
            // 
            this.publishYearTaker.AcceptsReturn = false;
            this.publishYearTaker.AcceptsTab = false;
            this.publishYearTaker.AnimationSpeed = 200;
            this.publishYearTaker.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.publishYearTaker.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.publishYearTaker.BackColor = System.Drawing.Color.White;
            this.publishYearTaker.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("publishYearTaker.BackgroundImage")));
            this.publishYearTaker.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.publishYearTaker.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.publishYearTaker.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.publishYearTaker.BorderColorIdle = System.Drawing.Color.Silver;
            this.publishYearTaker.BorderRadius = 1;
            this.publishYearTaker.BorderThickness = 1;
            this.publishYearTaker.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.publishYearTaker.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.publishYearTaker.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.publishYearTaker.DefaultText = "";
            this.publishYearTaker.FillColor = System.Drawing.Color.White;
            this.publishYearTaker.HideSelection = true;
            this.publishYearTaker.IconLeft = null;
            this.publishYearTaker.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.publishYearTaker.IconPadding = 10;
            this.publishYearTaker.IconRight = null;
            this.publishYearTaker.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.publishYearTaker.Lines = new string[0];
            this.publishYearTaker.Location = new System.Drawing.Point(83, 354);
            this.publishYearTaker.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.publishYearTaker.MaxLength = 32767;
            this.publishYearTaker.MinimumSize = new System.Drawing.Size(1, 1);
            this.publishYearTaker.Modified = false;
            this.publishYearTaker.Multiline = false;
            this.publishYearTaker.Name = "publishYearTaker";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.publishYearTaker.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.publishYearTaker.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.publishYearTaker.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.publishYearTaker.OnIdleState = stateProperties24;
            this.publishYearTaker.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.publishYearTaker.PasswordChar = '\0';
            this.publishYearTaker.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.publishYearTaker.PlaceholderText = "Năm xuất bản";
            this.publishYearTaker.ReadOnly = false;
            this.publishYearTaker.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.publishYearTaker.SelectedText = "";
            this.publishYearTaker.SelectionLength = 0;
            this.publishYearTaker.SelectionStart = 0;
            this.publishYearTaker.ShortcutsEnabled = true;
            this.publishYearTaker.Size = new System.Drawing.Size(347, 46);
            this.publishYearTaker.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.publishYearTaker.TabIndex = 3;
            this.publishYearTaker.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.publishYearTaker.TextMarginBottom = 0;
            this.publishYearTaker.TextMarginLeft = 3;
            this.publishYearTaker.TextMarginTop = 0;
            this.publishYearTaker.TextPlaceholder = "Năm xuất bản";
            this.publishYearTaker.UseSystemPasswordChar = false;
            this.publishYearTaker.WordWrap = true;
            // 
            // priceTaker
            // 
            this.priceTaker.AcceptsReturn = false;
            this.priceTaker.AcceptsTab = false;
            this.priceTaker.AnimationSpeed = 200;
            this.priceTaker.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.priceTaker.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.priceTaker.BackColor = System.Drawing.Color.White;
            this.priceTaker.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("priceTaker.BackgroundImage")));
            this.priceTaker.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.priceTaker.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.priceTaker.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.priceTaker.BorderColorIdle = System.Drawing.Color.Silver;
            this.priceTaker.BorderRadius = 1;
            this.priceTaker.BorderThickness = 1;
            this.priceTaker.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.priceTaker.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.priceTaker.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.priceTaker.DefaultText = "";
            this.priceTaker.FillColor = System.Drawing.Color.White;
            this.priceTaker.HideSelection = true;
            this.priceTaker.IconLeft = null;
            this.priceTaker.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.priceTaker.IconPadding = 10;
            this.priceTaker.IconRight = null;
            this.priceTaker.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.priceTaker.Lines = new string[0];
            this.priceTaker.Location = new System.Drawing.Point(83, 422);
            this.priceTaker.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.priceTaker.MaxLength = 32767;
            this.priceTaker.MinimumSize = new System.Drawing.Size(1, 1);
            this.priceTaker.Modified = false;
            this.priceTaker.Multiline = false;
            this.priceTaker.Name = "priceTaker";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.priceTaker.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.priceTaker.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.priceTaker.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.priceTaker.OnIdleState = stateProperties28;
            this.priceTaker.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.priceTaker.PasswordChar = '\0';
            this.priceTaker.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.priceTaker.PlaceholderText = "Trị giá";
            this.priceTaker.ReadOnly = false;
            this.priceTaker.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.priceTaker.SelectedText = "";
            this.priceTaker.SelectionLength = 0;
            this.priceTaker.SelectionStart = 0;
            this.priceTaker.ShortcutsEnabled = true;
            this.priceTaker.Size = new System.Drawing.Size(347, 46);
            this.priceTaker.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.priceTaker.TabIndex = 3;
            this.priceTaker.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.priceTaker.TextMarginBottom = 0;
            this.priceTaker.TextMarginLeft = 3;
            this.priceTaker.TextMarginTop = 0;
            this.priceTaker.TextPlaceholder = "Trị giá";
            this.priceTaker.UseSystemPasswordChar = false;
            this.priceTaker.WordWrap = true;
            // 
            // saveBt
            // 
            this.saveBt.AllowAnimations = true;
            this.saveBt.AllowMouseEffects = true;
            this.saveBt.AllowToggling = false;
            this.saveBt.AnimationSpeed = 200;
            this.saveBt.AutoGenerateColors = false;
            this.saveBt.AutoRoundBorders = false;
            this.saveBt.AutoSizeLeftIcon = true;
            this.saveBt.AutoSizeRightIcon = true;
            this.saveBt.BackColor = System.Drawing.Color.Transparent;
            this.saveBt.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.saveBt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("saveBt.BackgroundImage")));
            this.saveBt.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.saveBt.ButtonText = "Lưu";
            this.saveBt.ButtonTextMarginLeft = 0;
            this.saveBt.ColorContrastOnClick = 45;
            this.saveBt.ColorContrastOnHover = 45;
            this.saveBt.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.saveBt.CustomizableEdges = borderEdges1;
            this.saveBt.DialogResult = System.Windows.Forms.DialogResult.None;
            this.saveBt.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.saveBt.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.saveBt.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.saveBt.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.saveBt.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.saveBt.ForeColor = System.Drawing.Color.White;
            this.saveBt.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.saveBt.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.saveBt.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.saveBt.IconMarginLeft = 11;
            this.saveBt.IconPadding = 10;
            this.saveBt.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.saveBt.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.saveBt.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.saveBt.IconSize = 25;
            this.saveBt.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.saveBt.IdleBorderRadius = 1;
            this.saveBt.IdleBorderThickness = 1;
            this.saveBt.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.saveBt.IdleIconLeftImage = null;
            this.saveBt.IdleIconRightImage = null;
            this.saveBt.IndicateFocus = false;
            this.saveBt.Location = new System.Drawing.Point(763, 456);
            this.saveBt.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.saveBt.Name = "saveBt";
            this.saveBt.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.saveBt.OnDisabledState.BorderRadius = 1;
            this.saveBt.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.saveBt.OnDisabledState.BorderThickness = 1;
            this.saveBt.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.saveBt.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.saveBt.OnDisabledState.IconLeftImage = null;
            this.saveBt.OnDisabledState.IconRightImage = null;
            this.saveBt.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.saveBt.onHoverState.BorderRadius = 1;
            this.saveBt.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.saveBt.onHoverState.BorderThickness = 1;
            this.saveBt.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.saveBt.onHoverState.ForeColor = System.Drawing.Color.White;
            this.saveBt.onHoverState.IconLeftImage = null;
            this.saveBt.onHoverState.IconRightImage = null;
            this.saveBt.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.saveBt.OnIdleState.BorderRadius = 1;
            this.saveBt.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.saveBt.OnIdleState.BorderThickness = 1;
            this.saveBt.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.saveBt.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.saveBt.OnIdleState.IconLeftImage = null;
            this.saveBt.OnIdleState.IconRightImage = null;
            this.saveBt.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.saveBt.OnPressedState.BorderRadius = 1;
            this.saveBt.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.saveBt.OnPressedState.BorderThickness = 1;
            this.saveBt.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.saveBt.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.saveBt.OnPressedState.IconLeftImage = null;
            this.saveBt.OnPressedState.IconRightImage = null;
            this.saveBt.Size = new System.Drawing.Size(128, 32);
            this.saveBt.TabIndex = 5;
            this.saveBt.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.saveBt.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.saveBt.TextMarginLeft = 0;
            this.saveBt.TextPadding = new System.Windows.Forms.Padding(0);
            this.saveBt.UseDefaultRadiusAndThickness = true;
            this.saveBt.Click += new System.EventHandler(this.saveBt_Click);
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(525, 301);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(55, 17);
            this.label2.TabIndex = 6;
            this.label2.Text = "Tác giả";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(523, 365);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(59, 17);
            this.label3.TabIndex = 6;
            this.label3.Text = "Thể loại";
            // 
            // authorSet
            // 
            this.authorSet.BackColor = System.Drawing.Color.Transparent;
            this.authorSet.BackgroundColor = System.Drawing.Color.White;
            this.authorSet.BorderColor = System.Drawing.Color.Silver;
            this.authorSet.BorderRadius = 1;
            this.authorSet.Color = System.Drawing.Color.Silver;
            this.authorSet.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.authorSet.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.authorSet.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.authorSet.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.authorSet.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.authorSet.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.authorSet.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.authorSet.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.authorSet.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.authorSet.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.authorSet.FillDropDown = true;
            this.authorSet.FillIndicator = false;
            this.authorSet.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.authorSet.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.authorSet.ForeColor = System.Drawing.Color.Black;
            this.authorSet.FormattingEnabled = true;
            this.authorSet.Icon = null;
            this.authorSet.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.authorSet.IndicatorColor = System.Drawing.Color.Gray;
            this.authorSet.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.authorSet.ItemBackColor = System.Drawing.Color.White;
            this.authorSet.ItemBorderColor = System.Drawing.Color.White;
            this.authorSet.ItemForeColor = System.Drawing.Color.Black;
            this.authorSet.ItemHeight = 26;
            this.authorSet.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.authorSet.ItemHighLightForeColor = System.Drawing.Color.White;
            this.authorSet.ItemTopMargin = 3;
            this.authorSet.Location = new System.Drawing.Point(519, 320);
            this.authorSet.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.authorSet.Name = "authorSet";
            this.authorSet.Size = new System.Drawing.Size(347, 32);
            this.authorSet.TabIndex = 7;
            this.authorSet.Text = null;
            this.authorSet.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.authorSet.TextLeftMargin = 5;
            // 
            // genreSet
            // 
            this.genreSet.BackColor = System.Drawing.Color.Transparent;
            this.genreSet.BackgroundColor = System.Drawing.Color.White;
            this.genreSet.BorderColor = System.Drawing.Color.Silver;
            this.genreSet.BorderRadius = 1;
            this.genreSet.Color = System.Drawing.Color.Silver;
            this.genreSet.Direction = Bunifu.UI.WinForms.BunifuDropdown.Directions.Down;
            this.genreSet.DisabledBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.genreSet.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.genreSet.DisabledColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            this.genreSet.DisabledForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            this.genreSet.DisabledIndicatorColor = System.Drawing.Color.DarkGray;
            this.genreSet.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            this.genreSet.DropdownBorderThickness = Bunifu.UI.WinForms.BunifuDropdown.BorderThickness.Thin;
            this.genreSet.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.genreSet.DropDownTextAlign = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.genreSet.FillDropDown = true;
            this.genreSet.FillIndicator = false;
            this.genreSet.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
            this.genreSet.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.genreSet.ForeColor = System.Drawing.Color.Black;
            this.genreSet.FormattingEnabled = true;
            this.genreSet.Icon = null;
            this.genreSet.IndicatorAlignment = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.genreSet.IndicatorColor = System.Drawing.Color.Gray;
            this.genreSet.IndicatorLocation = Bunifu.UI.WinForms.BunifuDropdown.Indicator.Right;
            this.genreSet.ItemBackColor = System.Drawing.Color.White;
            this.genreSet.ItemBorderColor = System.Drawing.Color.White;
            this.genreSet.ItemForeColor = System.Drawing.Color.Black;
            this.genreSet.ItemHeight = 26;
            this.genreSet.ItemHighLightColor = System.Drawing.Color.DodgerBlue;
            this.genreSet.ItemHighLightForeColor = System.Drawing.Color.White;
            this.genreSet.ItemTopMargin = 3;
            this.genreSet.Location = new System.Drawing.Point(519, 385);
            this.genreSet.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.genreSet.Name = "genreSet";
            this.genreSet.Size = new System.Drawing.Size(347, 32);
            this.genreSet.TabIndex = 8;
            this.genreSet.Text = null;
            this.genreSet.TextAlignment = Bunifu.UI.WinForms.BunifuDropdown.TextAlign.Left;
            this.genreSet.TextLeftMargin = 5;
            // 
            // AddBookScreen
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Linen;
            this.ClientSize = new System.Drawing.Size(941, 514);
            this.Controls.Add(this.genreSet);
            this.Controls.Add(this.authorSet);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.saveBt);
            this.Controls.Add(this.statusTaker);
            this.Controls.Add(this.amountTaker);
            this.Controls.Add(this.publisherTaker);
            this.Controls.Add(this.priceTaker);
            this.Controls.Add(this.publishYearTaker);
            this.Controls.Add(this.posTaker);
            this.Controls.Add(this.nameTaker);
            this.Controls.Add(this.topPanel);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.Name = "AddBookScreen";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterScreen;
            this.Text = "Form1";
            this.topPanel.ResumeLayout(false);
            this.topPanel.PerformLayout();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private System.Windows.Forms.Panel topPanel;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuImageButton exitButton;
        private Bunifu.Framework.UI.BunifuDragControl bunifuDragControl1;
        private Bunifu.UI.WinForms.BunifuTextBox nameTaker;
        private Bunifu.UI.WinForms.BunifuTextBox posTaker;
        private Bunifu.UI.WinForms.BunifuTextBox publisherTaker;
        private Bunifu.UI.WinForms.BunifuTextBox amountTaker;
        private Bunifu.UI.WinForms.BunifuTextBox statusTaker;
        private Bunifu.UI.WinForms.BunifuTextBox publishYearTaker;
        private Bunifu.UI.WinForms.BunifuTextBox priceTaker;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton saveBt;
        private Bunifu.UI.WinForms.BunifuDatePicker todayGetter;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private Bunifu.UI.WinForms.BunifuDropdown authorSet;
        private Bunifu.UI.WinForms.BunifuDropdown genreSet;
    }
}