
namespace LibraryApp
{
    partial class IssuedBooks
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(IssuedBooks));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties1 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties2 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties3 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties4 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties5 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties6 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties7 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties8 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties9 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties10 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties11 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties12 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties13 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties14 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties15 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties16 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties17 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties18 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties19 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties20 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties21 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties22 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties23 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties24 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties25 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties26 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties27 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties28 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle1 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle2 = new System.Windows.Forms.DataGridViewCellStyle();
            System.Windows.Forms.DataGridViewCellStyle dataGridViewCellStyle3 = new System.Windows.Forms.DataGridViewCellStyle();
            this.label1 = new System.Windows.Forms.Label();
            this.label2 = new System.Windows.Forms.Label();
            this.label3 = new System.Windows.Forms.Label();
            this.bSearchBt = new Bunifu.UI.WinForms.BunifuImageButton();
            this.rSearchBt = new Bunifu.UI.WinForms.BunifuImageButton();
            this.addBookBt = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.saveBt = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.dateGetter = new Bunifu.UI.WinForms.BunifuDatePicker();
            this.rBirth = new Bunifu.UI.WinForms.BunifuTextBox();
            this.rEmail = new Bunifu.UI.WinForms.BunifuTextBox();
            this.rAddress = new Bunifu.UI.WinForms.BunifuTextBox();
            this.rName = new Bunifu.UI.WinForms.BunifuTextBox();
            this.nameBook = new Bunifu.UI.WinForms.BunifuTextBox();
            this.bIdTaker = new Bunifu.UI.WinForms.BunifuTextBox();
            this.rIdTaker = new Bunifu.UI.WinForms.BunifuTextBox();
            this.label4 = new System.Windows.Forms.Label();
            this.label5 = new System.Windows.Forms.Label();
            this.label6 = new System.Windows.Forms.Label();
            this.label7 = new System.Windows.Forms.Label();
            this.delBt = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.bookData = new Bunifu.UI.WinForms.BunifuDataGridView();
            this.bID = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.bookName = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.status = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.price = new System.Windows.Forms.DataGridViewTextBoxColumn();
            ((System.ComponentModel.ISupportInitialize)(this.bookData)).BeginInit();
            this.SuspendLayout();
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 13.8F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.Location = new System.Drawing.Point(389, 316);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(199, 29);
            this.label1.TabIndex = 5;
            this.label1.Text = "Thông tin độc giả";
            // 
            // label2
            // 
            this.label2.AutoSize = true;
            this.label2.Location = new System.Drawing.Point(847, 436);
            this.label2.Name = "label2";
            this.label2.Size = new System.Drawing.Size(67, 17);
            this.label2.TabIndex = 11;
            this.label2.Text = "Tên sách";
            // 
            // label3
            // 
            this.label3.AutoSize = true;
            this.label3.Location = new System.Drawing.Point(845, 382);
            this.label3.Name = "label3";
            this.label3.Size = new System.Drawing.Size(80, 17);
            this.label3.TabIndex = 11;
            this.label3.Text = "Ngày mượn";
            // 
            // bSearchBt
            // 
            this.bSearchBt.ActiveImage = null;
            this.bSearchBt.AllowAnimations = true;
            this.bSearchBt.AllowBuffering = false;
            this.bSearchBt.AllowToggling = false;
            this.bSearchBt.AllowZooming = true;
            this.bSearchBt.AllowZoomingOnFocus = false;
            this.bSearchBt.BackColor = System.Drawing.Color.Transparent;
            this.bSearchBt.DialogResult = System.Windows.Forms.DialogResult.None;
            this.bSearchBt.ErrorImage = ((System.Drawing.Image)(resources.GetObject("bSearchBt.ErrorImage")));
            this.bSearchBt.FadeWhenInactive = false;
            this.bSearchBt.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.bSearchBt.Image = ((System.Drawing.Image)(resources.GetObject("bSearchBt.Image")));
            this.bSearchBt.ImageActive = null;
            this.bSearchBt.ImageLocation = null;
            this.bSearchBt.ImageMargin = 0;
            this.bSearchBt.ImageSize = new System.Drawing.Size(28, 29);
            this.bSearchBt.ImageZoomSize = new System.Drawing.Size(29, 30);
            this.bSearchBt.InitialImage = ((System.Drawing.Image)(resources.GetObject("bSearchBt.InitialImage")));
            this.bSearchBt.Location = new System.Drawing.Point(1140, 258);
            this.bSearchBt.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.bSearchBt.Name = "bSearchBt";
            this.bSearchBt.Rotation = 0;
            this.bSearchBt.ShowActiveImage = true;
            this.bSearchBt.ShowCursorChanges = true;
            this.bSearchBt.ShowImageBorders = true;
            this.bSearchBt.ShowSizeMarkers = false;
            this.bSearchBt.Size = new System.Drawing.Size(29, 30);
            this.bSearchBt.TabIndex = 9;
            this.bSearchBt.ToolTipText = "";
            this.bSearchBt.WaitOnLoad = false;
            this.bSearchBt.Zoom = 0;
            this.bSearchBt.ZoomSpeed = 10;
            this.bSearchBt.Click += new System.EventHandler(this.bSearchBt_Click);
            // 
            // rSearchBt
            // 
            this.rSearchBt.ActiveImage = null;
            this.rSearchBt.AllowAnimations = true;
            this.rSearchBt.AllowBuffering = false;
            this.rSearchBt.AllowToggling = false;
            this.rSearchBt.AllowZooming = true;
            this.rSearchBt.AllowZoomingOnFocus = false;
            this.rSearchBt.BackColor = System.Drawing.Color.Transparent;
            this.rSearchBt.DialogResult = System.Windows.Forms.DialogResult.None;
            this.rSearchBt.ErrorImage = ((System.Drawing.Image)(resources.GetObject("rSearchBt.ErrorImage")));
            this.rSearchBt.FadeWhenInactive = false;
            this.rSearchBt.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.rSearchBt.Image = ((System.Drawing.Image)(resources.GetObject("rSearchBt.Image")));
            this.rSearchBt.ImageActive = null;
            this.rSearchBt.ImageLocation = null;
            this.rSearchBt.ImageMargin = 0;
            this.rSearchBt.ImageSize = new System.Drawing.Size(28, 29);
            this.rSearchBt.ImageZoomSize = new System.Drawing.Size(29, 30);
            this.rSearchBt.InitialImage = ((System.Drawing.Image)(resources.GetObject("rSearchBt.InitialImage")));
            this.rSearchBt.Location = new System.Drawing.Point(632, 258);
            this.rSearchBt.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.rSearchBt.Name = "rSearchBt";
            this.rSearchBt.Rotation = 0;
            this.rSearchBt.ShowActiveImage = true;
            this.rSearchBt.ShowCursorChanges = true;
            this.rSearchBt.ShowImageBorders = true;
            this.rSearchBt.ShowSizeMarkers = false;
            this.rSearchBt.Size = new System.Drawing.Size(29, 30);
            this.rSearchBt.TabIndex = 9;
            this.rSearchBt.ToolTipText = "";
            this.rSearchBt.WaitOnLoad = false;
            this.rSearchBt.Zoom = 0;
            this.rSearchBt.ZoomSpeed = 10;
            this.rSearchBt.Click += new System.EventHandler(this.rSearchBt_Click);
            // 
            // addBookBt
            // 
            this.addBookBt.AllowAnimations = true;
            this.addBookBt.AllowMouseEffects = true;
            this.addBookBt.AllowToggling = false;
            this.addBookBt.AnimationSpeed = 200;
            this.addBookBt.AutoGenerateColors = false;
            this.addBookBt.AutoRoundBorders = false;
            this.addBookBt.AutoSizeLeftIcon = true;
            this.addBookBt.AutoSizeRightIcon = true;
            this.addBookBt.BackColor = System.Drawing.Color.Transparent;
            this.addBookBt.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.addBookBt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("addBookBt.BackgroundImage")));
            this.addBookBt.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addBookBt.ButtonText = "Thêm sách";
            this.addBookBt.ButtonTextMarginLeft = 0;
            this.addBookBt.ColorContrastOnClick = 45;
            this.addBookBt.ColorContrastOnHover = 45;
            this.addBookBt.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            this.addBookBt.CustomizableEdges = borderEdges1;
            this.addBookBt.DialogResult = System.Windows.Forms.DialogResult.None;
            this.addBookBt.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.addBookBt.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addBookBt.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.addBookBt.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.addBookBt.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.addBookBt.ForeColor = System.Drawing.Color.White;
            this.addBookBt.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.addBookBt.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.addBookBt.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.addBookBt.IconMarginLeft = 11;
            this.addBookBt.IconPadding = 10;
            this.addBookBt.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.addBookBt.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.addBookBt.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.addBookBt.IconSize = 25;
            this.addBookBt.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.addBookBt.IdleBorderRadius = 1;
            this.addBookBt.IdleBorderThickness = 1;
            this.addBookBt.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.addBookBt.IdleIconLeftImage = null;
            this.addBookBt.IdleIconRightImage = null;
            this.addBookBt.IndicateFocus = false;
            this.addBookBt.Location = new System.Drawing.Point(903, 511);
            this.addBookBt.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.addBookBt.Name = "addBookBt";
            this.addBookBt.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.addBookBt.OnDisabledState.BorderRadius = 1;
            this.addBookBt.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addBookBt.OnDisabledState.BorderThickness = 1;
            this.addBookBt.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.addBookBt.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.addBookBt.OnDisabledState.IconLeftImage = null;
            this.addBookBt.OnDisabledState.IconRightImage = null;
            this.addBookBt.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addBookBt.onHoverState.BorderRadius = 1;
            this.addBookBt.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addBookBt.onHoverState.BorderThickness = 1;
            this.addBookBt.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.addBookBt.onHoverState.ForeColor = System.Drawing.Color.White;
            this.addBookBt.onHoverState.IconLeftImage = null;
            this.addBookBt.onHoverState.IconRightImage = null;
            this.addBookBt.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.addBookBt.OnIdleState.BorderRadius = 1;
            this.addBookBt.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addBookBt.OnIdleState.BorderThickness = 1;
            this.addBookBt.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.addBookBt.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.addBookBt.OnIdleState.IconLeftImage = null;
            this.addBookBt.OnIdleState.IconRightImage = null;
            this.addBookBt.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.addBookBt.OnPressedState.BorderRadius = 1;
            this.addBookBt.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.addBookBt.OnPressedState.BorderThickness = 1;
            this.addBookBt.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.addBookBt.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.addBookBt.OnPressedState.IconLeftImage = null;
            this.addBookBt.OnPressedState.IconRightImage = null;
            this.addBookBt.Size = new System.Drawing.Size(149, 39);
            this.addBookBt.TabIndex = 7;
            this.addBookBt.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.addBookBt.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.addBookBt.TextMarginLeft = 0;
            this.addBookBt.TextPadding = new System.Windows.Forms.Padding(0);
            this.addBookBt.UseDefaultRadiusAndThickness = true;
            this.addBookBt.Click += new System.EventHandler(this.addBookBt_Click);
            // 
            // saveBt
            // 
            this.saveBt.AllowAnimations = true;
            this.saveBt.AllowMouseEffects = true;
            this.saveBt.AllowToggling = false;
            this.saveBt.AnimationSpeed = 200;
            this.saveBt.AutoGenerateColors = false;
            this.saveBt.AutoRoundBorders = false;
            this.saveBt.AutoSizeLeftIcon = true;
            this.saveBt.AutoSizeRightIcon = true;
            this.saveBt.BackColor = System.Drawing.Color.Transparent;
            this.saveBt.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.saveBt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("saveBt.BackgroundImage")));
            this.saveBt.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.saveBt.ButtonText = "Lưu";
            this.saveBt.ButtonTextMarginLeft = 0;
            this.saveBt.ColorContrastOnClick = 45;
            this.saveBt.ColorContrastOnHover = 45;
            this.saveBt.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.saveBt.CustomizableEdges = borderEdges2;
            this.saveBt.DialogResult = System.Windows.Forms.DialogResult.None;
            this.saveBt.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.saveBt.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.saveBt.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.saveBt.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.saveBt.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.saveBt.ForeColor = System.Drawing.Color.White;
            this.saveBt.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.saveBt.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.saveBt.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.saveBt.IconMarginLeft = 11;
            this.saveBt.IconPadding = 10;
            this.saveBt.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.saveBt.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.saveBt.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.saveBt.IconSize = 25;
            this.saveBt.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.saveBt.IdleBorderRadius = 1;
            this.saveBt.IdleBorderThickness = 1;
            this.saveBt.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.saveBt.IdleIconLeftImage = null;
            this.saveBt.IdleIconRightImage = null;
            this.saveBt.IndicateFocus = false;
            this.saveBt.Location = new System.Drawing.Point(1217, 599);
            this.saveBt.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.saveBt.Name = "saveBt";
            this.saveBt.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.saveBt.OnDisabledState.BorderRadius = 1;
            this.saveBt.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.saveBt.OnDisabledState.BorderThickness = 1;
            this.saveBt.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.saveBt.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.saveBt.OnDisabledState.IconLeftImage = null;
            this.saveBt.OnDisabledState.IconRightImage = null;
            this.saveBt.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.saveBt.onHoverState.BorderRadius = 1;
            this.saveBt.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.saveBt.onHoverState.BorderThickness = 1;
            this.saveBt.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.saveBt.onHoverState.ForeColor = System.Drawing.Color.White;
            this.saveBt.onHoverState.IconLeftImage = null;
            this.saveBt.onHoverState.IconRightImage = null;
            this.saveBt.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.saveBt.OnIdleState.BorderRadius = 1;
            this.saveBt.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.saveBt.OnIdleState.BorderThickness = 1;
            this.saveBt.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.saveBt.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.saveBt.OnIdleState.IconLeftImage = null;
            this.saveBt.OnIdleState.IconRightImage = null;
            this.saveBt.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.saveBt.OnPressedState.BorderRadius = 1;
            this.saveBt.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.saveBt.OnPressedState.BorderThickness = 1;
            this.saveBt.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.saveBt.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.saveBt.OnPressedState.IconLeftImage = null;
            this.saveBt.OnPressedState.IconRightImage = null;
            this.saveBt.Size = new System.Drawing.Size(149, 39);
            this.saveBt.TabIndex = 7;
            this.saveBt.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.saveBt.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.saveBt.TextMarginLeft = 0;
            this.saveBt.TextPadding = new System.Windows.Forms.Padding(0);
            this.saveBt.UseDefaultRadiusAndThickness = true;
            this.saveBt.Click += new System.EventHandler(this.saveBt_Click);
            // 
            // dateGetter
            // 
            this.dateGetter.BackColor = System.Drawing.Color.Transparent;
            this.dateGetter.BorderRadius = 1;
            this.dateGetter.Color = System.Drawing.Color.Silver;
            this.dateGetter.CustomFormat = "dd MM yyyy";
            this.dateGetter.DateBorderThickness = Bunifu.UI.WinForms.BunifuDatePicker.BorderThickness.Thin;
            this.dateGetter.DateTextAlign = Bunifu.UI.WinForms.BunifuDatePicker.TextAlign.Left;
            this.dateGetter.DisabledColor = System.Drawing.Color.Gray;
            this.dateGetter.DisplayWeekNumbers = false;
            this.dateGetter.DPHeight = 0;
            this.dateGetter.DropDownAlign = System.Windows.Forms.LeftRightAlignment.Right;
            this.dateGetter.FillDatePicker = false;
            this.dateGetter.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.dateGetter.ForeColor = System.Drawing.Color.Black;
            this.dateGetter.Icon = ((System.Drawing.Image)(resources.GetObject("dateGetter.Icon")));
            this.dateGetter.IconColor = System.Drawing.Color.Gray;
            this.dateGetter.IconLocation = Bunifu.UI.WinForms.BunifuDatePicker.Indicator.Right;
            this.dateGetter.LeftTextMargin = 5;
            this.dateGetter.Location = new System.Drawing.Point(933, 382);
            this.dateGetter.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.dateGetter.MinimumSize = new System.Drawing.Size(4, 32);
            this.dateGetter.Name = "dateGetter";
            this.dateGetter.Size = new System.Drawing.Size(259, 32);
            this.dateGetter.TabIndex = 6;
            // 
            // rBirth
            // 
            this.rBirth.AcceptsReturn = false;
            this.rBirth.AcceptsTab = false;
            this.rBirth.AnimationSpeed = 200;
            this.rBirth.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.rBirth.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.rBirth.BackColor = System.Drawing.Color.White;
            this.rBirth.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("rBirth.BackgroundImage")));
            this.rBirth.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.rBirth.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.rBirth.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.rBirth.BorderColorIdle = System.Drawing.Color.Silver;
            this.rBirth.BorderRadius = 1;
            this.rBirth.BorderThickness = 1;
            this.rBirth.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.rBirth.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.rBirth.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.rBirth.DefaultText = "";
            this.rBirth.FillColor = System.Drawing.Color.White;
            this.rBirth.HideSelection = true;
            this.rBirth.IconLeft = null;
            this.rBirth.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.rBirth.IconPadding = 10;
            this.rBirth.IconRight = null;
            this.rBirth.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.rBirth.Lines = new string[0];
            this.rBirth.Location = new System.Drawing.Point(463, 475);
            this.rBirth.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.rBirth.MaxLength = 32767;
            this.rBirth.MinimumSize = new System.Drawing.Size(1, 1);
            this.rBirth.Modified = false;
            this.rBirth.Multiline = false;
            this.rBirth.Name = "rBirth";
            stateProperties1.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties1.FillColor = System.Drawing.Color.Empty;
            stateProperties1.ForeColor = System.Drawing.Color.Empty;
            stateProperties1.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.rBirth.OnActiveState = stateProperties1;
            stateProperties2.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties2.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties2.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties2.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.rBirth.OnDisabledState = stateProperties2;
            stateProperties3.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties3.FillColor = System.Drawing.Color.Empty;
            stateProperties3.ForeColor = System.Drawing.Color.Empty;
            stateProperties3.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.rBirth.OnHoverState = stateProperties3;
            stateProperties4.BorderColor = System.Drawing.Color.Silver;
            stateProperties4.FillColor = System.Drawing.Color.White;
            stateProperties4.ForeColor = System.Drawing.Color.Empty;
            stateProperties4.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.rBirth.OnIdleState = stateProperties4;
            this.rBirth.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.rBirth.PasswordChar = '\0';
            this.rBirth.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.rBirth.PlaceholderText = "";
            this.rBirth.ReadOnly = true;
            this.rBirth.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.rBirth.SelectedText = "";
            this.rBirth.SelectionLength = 0;
            this.rBirth.SelectionStart = 0;
            this.rBirth.ShortcutsEnabled = true;
            this.rBirth.Size = new System.Drawing.Size(260, 49);
            this.rBirth.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.rBirth.TabIndex = 4;
            this.rBirth.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.rBirth.TextMarginBottom = 0;
            this.rBirth.TextMarginLeft = 3;
            this.rBirth.TextMarginTop = 0;
            this.rBirth.TextPlaceholder = "";
            this.rBirth.UseSystemPasswordChar = false;
            this.rBirth.WordWrap = true;
            // 
            // rEmail
            // 
            this.rEmail.AcceptsReturn = false;
            this.rEmail.AcceptsTab = false;
            this.rEmail.AnimationSpeed = 200;
            this.rEmail.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.rEmail.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.rEmail.BackColor = System.Drawing.Color.White;
            this.rEmail.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("rEmail.BackgroundImage")));
            this.rEmail.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.rEmail.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.rEmail.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.rEmail.BorderColorIdle = System.Drawing.Color.Silver;
            this.rEmail.BorderRadius = 1;
            this.rEmail.BorderThickness = 1;
            this.rEmail.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.rEmail.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.rEmail.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.rEmail.DefaultText = "";
            this.rEmail.FillColor = System.Drawing.Color.White;
            this.rEmail.HideSelection = true;
            this.rEmail.IconLeft = null;
            this.rEmail.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.rEmail.IconPadding = 10;
            this.rEmail.IconRight = null;
            this.rEmail.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.rEmail.Lines = new string[0];
            this.rEmail.Location = new System.Drawing.Point(463, 420);
            this.rEmail.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.rEmail.MaxLength = 32767;
            this.rEmail.MinimumSize = new System.Drawing.Size(1, 1);
            this.rEmail.Modified = false;
            this.rEmail.Multiline = false;
            this.rEmail.Name = "rEmail";
            stateProperties5.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties5.FillColor = System.Drawing.Color.Empty;
            stateProperties5.ForeColor = System.Drawing.Color.Empty;
            stateProperties5.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.rEmail.OnActiveState = stateProperties5;
            stateProperties6.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties6.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties6.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties6.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.rEmail.OnDisabledState = stateProperties6;
            stateProperties7.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties7.FillColor = System.Drawing.Color.Empty;
            stateProperties7.ForeColor = System.Drawing.Color.Empty;
            stateProperties7.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.rEmail.OnHoverState = stateProperties7;
            stateProperties8.BorderColor = System.Drawing.Color.Silver;
            stateProperties8.FillColor = System.Drawing.Color.White;
            stateProperties8.ForeColor = System.Drawing.Color.Empty;
            stateProperties8.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.rEmail.OnIdleState = stateProperties8;
            this.rEmail.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.rEmail.PasswordChar = '\0';
            this.rEmail.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.rEmail.PlaceholderText = "";
            this.rEmail.ReadOnly = true;
            this.rEmail.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.rEmail.SelectedText = "";
            this.rEmail.SelectionLength = 0;
            this.rEmail.SelectionStart = 0;
            this.rEmail.ShortcutsEnabled = true;
            this.rEmail.Size = new System.Drawing.Size(260, 49);
            this.rEmail.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.rEmail.TabIndex = 4;
            this.rEmail.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.rEmail.TextMarginBottom = 0;
            this.rEmail.TextMarginLeft = 3;
            this.rEmail.TextMarginTop = 0;
            this.rEmail.TextPlaceholder = "";
            this.rEmail.UseSystemPasswordChar = false;
            this.rEmail.WordWrap = true;
            // 
            // rAddress
            // 
            this.rAddress.AcceptsReturn = false;
            this.rAddress.AcceptsTab = false;
            this.rAddress.AnimationSpeed = 200;
            this.rAddress.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.rAddress.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.rAddress.BackColor = System.Drawing.Color.White;
            this.rAddress.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("rAddress.BackgroundImage")));
            this.rAddress.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.rAddress.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.rAddress.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.rAddress.BorderColorIdle = System.Drawing.Color.Silver;
            this.rAddress.BorderRadius = 1;
            this.rAddress.BorderThickness = 1;
            this.rAddress.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.rAddress.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.rAddress.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.rAddress.DefaultText = "";
            this.rAddress.FillColor = System.Drawing.Color.White;
            this.rAddress.HideSelection = true;
            this.rAddress.IconLeft = null;
            this.rAddress.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.rAddress.IconPadding = 10;
            this.rAddress.IconRight = null;
            this.rAddress.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.rAddress.Lines = new string[0];
            this.rAddress.Location = new System.Drawing.Point(463, 530);
            this.rAddress.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.rAddress.MaxLength = 32767;
            this.rAddress.MinimumSize = new System.Drawing.Size(1, 1);
            this.rAddress.Modified = false;
            this.rAddress.Multiline = false;
            this.rAddress.Name = "rAddress";
            stateProperties9.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties9.FillColor = System.Drawing.Color.Empty;
            stateProperties9.ForeColor = System.Drawing.Color.Empty;
            stateProperties9.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.rAddress.OnActiveState = stateProperties9;
            stateProperties10.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties10.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties10.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties10.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.rAddress.OnDisabledState = stateProperties10;
            stateProperties11.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties11.FillColor = System.Drawing.Color.Empty;
            stateProperties11.ForeColor = System.Drawing.Color.Empty;
            stateProperties11.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.rAddress.OnHoverState = stateProperties11;
            stateProperties12.BorderColor = System.Drawing.Color.Silver;
            stateProperties12.FillColor = System.Drawing.Color.White;
            stateProperties12.ForeColor = System.Drawing.Color.Empty;
            stateProperties12.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.rAddress.OnIdleState = stateProperties12;
            this.rAddress.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.rAddress.PasswordChar = '\0';
            this.rAddress.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.rAddress.PlaceholderText = "";
            this.rAddress.ReadOnly = true;
            this.rAddress.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.rAddress.SelectedText = "";
            this.rAddress.SelectionLength = 0;
            this.rAddress.SelectionStart = 0;
            this.rAddress.ShortcutsEnabled = true;
            this.rAddress.Size = new System.Drawing.Size(260, 49);
            this.rAddress.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.rAddress.TabIndex = 4;
            this.rAddress.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.rAddress.TextMarginBottom = 0;
            this.rAddress.TextMarginLeft = 3;
            this.rAddress.TextMarginTop = 0;
            this.rAddress.TextPlaceholder = "";
            this.rAddress.UseSystemPasswordChar = false;
            this.rAddress.WordWrap = true;
            // 
            // rName
            // 
            this.rName.AcceptsReturn = false;
            this.rName.AcceptsTab = false;
            this.rName.AnimationSpeed = 200;
            this.rName.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.rName.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.rName.BackColor = System.Drawing.Color.White;
            this.rName.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("rName.BackgroundImage")));
            this.rName.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.rName.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.rName.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.rName.BorderColorIdle = System.Drawing.Color.Silver;
            this.rName.BorderRadius = 1;
            this.rName.BorderThickness = 1;
            this.rName.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.rName.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.rName.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.rName.DefaultText = "";
            this.rName.FillColor = System.Drawing.Color.White;
            this.rName.HideSelection = true;
            this.rName.IconLeft = null;
            this.rName.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.rName.IconPadding = 10;
            this.rName.IconRight = null;
            this.rName.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.rName.Lines = new string[0];
            this.rName.Location = new System.Drawing.Point(463, 366);
            this.rName.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.rName.MaxLength = 32767;
            this.rName.MinimumSize = new System.Drawing.Size(1, 1);
            this.rName.Modified = false;
            this.rName.Multiline = false;
            this.rName.Name = "rName";
            stateProperties13.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties13.FillColor = System.Drawing.Color.Empty;
            stateProperties13.ForeColor = System.Drawing.Color.Empty;
            stateProperties13.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.rName.OnActiveState = stateProperties13;
            stateProperties14.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties14.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties14.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties14.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.rName.OnDisabledState = stateProperties14;
            stateProperties15.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties15.FillColor = System.Drawing.Color.Empty;
            stateProperties15.ForeColor = System.Drawing.Color.Empty;
            stateProperties15.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.rName.OnHoverState = stateProperties15;
            stateProperties16.BorderColor = System.Drawing.Color.Silver;
            stateProperties16.FillColor = System.Drawing.Color.White;
            stateProperties16.ForeColor = System.Drawing.Color.Empty;
            stateProperties16.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.rName.OnIdleState = stateProperties16;
            this.rName.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.rName.PasswordChar = '\0';
            this.rName.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.rName.PlaceholderText = "";
            this.rName.ReadOnly = true;
            this.rName.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.rName.SelectedText = "";
            this.rName.SelectionLength = 0;
            this.rName.SelectionStart = 0;
            this.rName.ShortcutsEnabled = true;
            this.rName.Size = new System.Drawing.Size(260, 49);
            this.rName.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Bunifu;
            this.rName.TabIndex = 2;
            this.rName.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.rName.TextMarginBottom = 0;
            this.rName.TextMarginLeft = 3;
            this.rName.TextMarginTop = 0;
            this.rName.TextPlaceholder = "";
            this.rName.UseSystemPasswordChar = false;
            this.rName.WordWrap = true;
            // 
            // nameBook
            // 
            this.nameBook.AcceptsReturn = false;
            this.nameBook.AcceptsTab = false;
            this.nameBook.AnimationSpeed = 200;
            this.nameBook.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.nameBook.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.nameBook.BackColor = System.Drawing.Color.White;
            this.nameBook.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("nameBook.BackgroundImage")));
            this.nameBook.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.nameBook.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.nameBook.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.nameBook.BorderColorIdle = System.Drawing.Color.Silver;
            this.nameBook.BorderRadius = 1;
            this.nameBook.BorderThickness = 1;
            this.nameBook.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.nameBook.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.nameBook.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.nameBook.DefaultText = "";
            this.nameBook.FillColor = System.Drawing.Color.White;
            this.nameBook.HideSelection = true;
            this.nameBook.IconLeft = null;
            this.nameBook.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.nameBook.IconPadding = 10;
            this.nameBook.IconRight = null;
            this.nameBook.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.nameBook.Lines = new string[0];
            this.nameBook.Location = new System.Drawing.Point(933, 436);
            this.nameBook.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.nameBook.MaxLength = 32767;
            this.nameBook.MinimumSize = new System.Drawing.Size(1, 1);
            this.nameBook.Modified = false;
            this.nameBook.Multiline = false;
            this.nameBook.Name = "nameBook";
            stateProperties17.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties17.FillColor = System.Drawing.Color.Empty;
            stateProperties17.ForeColor = System.Drawing.Color.Empty;
            stateProperties17.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nameBook.OnActiveState = stateProperties17;
            stateProperties18.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties18.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties18.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties18.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.nameBook.OnDisabledState = stateProperties18;
            stateProperties19.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties19.FillColor = System.Drawing.Color.Empty;
            stateProperties19.ForeColor = System.Drawing.Color.Empty;
            stateProperties19.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nameBook.OnHoverState = stateProperties19;
            stateProperties20.BorderColor = System.Drawing.Color.Silver;
            stateProperties20.FillColor = System.Drawing.Color.White;
            stateProperties20.ForeColor = System.Drawing.Color.Empty;
            stateProperties20.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nameBook.OnIdleState = stateProperties20;
            this.nameBook.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.nameBook.PasswordChar = '\0';
            this.nameBook.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.nameBook.PlaceholderText = "";
            this.nameBook.ReadOnly = true;
            this.nameBook.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.nameBook.SelectedText = "";
            this.nameBook.SelectionLength = 0;
            this.nameBook.SelectionStart = 0;
            this.nameBook.ShortcutsEnabled = true;
            this.nameBook.Size = new System.Drawing.Size(260, 49);
            this.nameBook.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.nameBook.TabIndex = 0;
            this.nameBook.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.nameBook.TextMarginBottom = 0;
            this.nameBook.TextMarginLeft = 3;
            this.nameBook.TextMarginTop = 0;
            this.nameBook.TextPlaceholder = "";
            this.nameBook.UseSystemPasswordChar = false;
            this.nameBook.WordWrap = true;
            // 
            // bIdTaker
            // 
            this.bIdTaker.AcceptsReturn = false;
            this.bIdTaker.AcceptsTab = false;
            this.bIdTaker.AnimationSpeed = 200;
            this.bIdTaker.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.bIdTaker.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.bIdTaker.BackColor = System.Drawing.Color.White;
            this.bIdTaker.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("bIdTaker.BackgroundImage")));
            this.bIdTaker.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.bIdTaker.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.bIdTaker.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.bIdTaker.BorderColorIdle = System.Drawing.Color.Silver;
            this.bIdTaker.BorderRadius = 1;
            this.bIdTaker.BorderThickness = 1;
            this.bIdTaker.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.bIdTaker.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.bIdTaker.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.bIdTaker.DefaultText = "";
            this.bIdTaker.FillColor = System.Drawing.Color.White;
            this.bIdTaker.HideSelection = true;
            this.bIdTaker.IconLeft = null;
            this.bIdTaker.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.bIdTaker.IconPadding = 10;
            this.bIdTaker.IconRight = null;
            this.bIdTaker.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.bIdTaker.Lines = new string[0];
            this.bIdTaker.Location = new System.Drawing.Point(851, 239);
            this.bIdTaker.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.bIdTaker.MaxLength = 32767;
            this.bIdTaker.MinimumSize = new System.Drawing.Size(1, 1);
            this.bIdTaker.Modified = false;
            this.bIdTaker.Multiline = false;
            this.bIdTaker.Name = "bIdTaker";
            stateProperties21.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties21.FillColor = System.Drawing.Color.Empty;
            stateProperties21.ForeColor = System.Drawing.Color.Empty;
            stateProperties21.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bIdTaker.OnActiveState = stateProperties21;
            stateProperties22.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties22.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties22.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties22.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.bIdTaker.OnDisabledState = stateProperties22;
            stateProperties23.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties23.FillColor = System.Drawing.Color.Empty;
            stateProperties23.ForeColor = System.Drawing.Color.Empty;
            stateProperties23.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bIdTaker.OnHoverState = stateProperties23;
            stateProperties24.BorderColor = System.Drawing.Color.Silver;
            stateProperties24.FillColor = System.Drawing.Color.White;
            stateProperties24.ForeColor = System.Drawing.Color.Empty;
            stateProperties24.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.bIdTaker.OnIdleState = stateProperties24;
            this.bIdTaker.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.bIdTaker.PasswordChar = '\0';
            this.bIdTaker.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.bIdTaker.PlaceholderText = "Mã sách";
            this.bIdTaker.ReadOnly = false;
            this.bIdTaker.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.bIdTaker.SelectedText = "";
            this.bIdTaker.SelectionLength = 0;
            this.bIdTaker.SelectionStart = 0;
            this.bIdTaker.ShortcutsEnabled = true;
            this.bIdTaker.Size = new System.Drawing.Size(260, 49);
            this.bIdTaker.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.bIdTaker.TabIndex = 0;
            this.bIdTaker.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.bIdTaker.TextMarginBottom = 0;
            this.bIdTaker.TextMarginLeft = 3;
            this.bIdTaker.TextMarginTop = 0;
            this.bIdTaker.TextPlaceholder = "Mã sách";
            this.bIdTaker.UseSystemPasswordChar = false;
            this.bIdTaker.WordWrap = true;
            this.bIdTaker.TextChanged += new System.EventHandler(this.bIdTaker_TextChanged);
            // 
            // rIdTaker
            // 
            this.rIdTaker.AcceptsReturn = false;
            this.rIdTaker.AcceptsTab = false;
            this.rIdTaker.AnimationSpeed = 200;
            this.rIdTaker.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.rIdTaker.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.rIdTaker.BackColor = System.Drawing.Color.White;
            this.rIdTaker.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("rIdTaker.BackgroundImage")));
            this.rIdTaker.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.rIdTaker.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.rIdTaker.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.rIdTaker.BorderColorIdle = System.Drawing.Color.Silver;
            this.rIdTaker.BorderRadius = 1;
            this.rIdTaker.BorderThickness = 1;
            this.rIdTaker.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.rIdTaker.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.rIdTaker.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.rIdTaker.DefaultText = "";
            this.rIdTaker.FillColor = System.Drawing.Color.White;
            this.rIdTaker.HideSelection = true;
            this.rIdTaker.IconLeft = null;
            this.rIdTaker.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.rIdTaker.IconPadding = 10;
            this.rIdTaker.IconRight = null;
            this.rIdTaker.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.rIdTaker.Lines = new string[0];
            this.rIdTaker.Location = new System.Drawing.Point(352, 239);
            this.rIdTaker.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.rIdTaker.MaxLength = 32767;
            this.rIdTaker.MinimumSize = new System.Drawing.Size(1, 1);
            this.rIdTaker.Modified = false;
            this.rIdTaker.Multiline = false;
            this.rIdTaker.Name = "rIdTaker";
            stateProperties25.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties25.FillColor = System.Drawing.Color.Empty;
            stateProperties25.ForeColor = System.Drawing.Color.Empty;
            stateProperties25.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.rIdTaker.OnActiveState = stateProperties25;
            stateProperties26.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties26.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties26.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties26.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.rIdTaker.OnDisabledState = stateProperties26;
            stateProperties27.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties27.FillColor = System.Drawing.Color.Empty;
            stateProperties27.ForeColor = System.Drawing.Color.Empty;
            stateProperties27.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.rIdTaker.OnHoverState = stateProperties27;
            stateProperties28.BorderColor = System.Drawing.Color.Silver;
            stateProperties28.FillColor = System.Drawing.Color.White;
            stateProperties28.ForeColor = System.Drawing.Color.Empty;
            stateProperties28.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.rIdTaker.OnIdleState = stateProperties28;
            this.rIdTaker.Padding = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.rIdTaker.PasswordChar = '\0';
            this.rIdTaker.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.rIdTaker.PlaceholderText = "Mã độc giả";
            this.rIdTaker.ReadOnly = false;
            this.rIdTaker.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.rIdTaker.SelectedText = "";
            this.rIdTaker.SelectionLength = 0;
            this.rIdTaker.SelectionStart = 0;
            this.rIdTaker.ShortcutsEnabled = true;
            this.rIdTaker.Size = new System.Drawing.Size(260, 49);
            this.rIdTaker.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.rIdTaker.TabIndex = 0;
            this.rIdTaker.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.rIdTaker.TextMarginBottom = 0;
            this.rIdTaker.TextMarginLeft = 3;
            this.rIdTaker.TextMarginTop = 0;
            this.rIdTaker.TextPlaceholder = "Mã độc giả";
            this.rIdTaker.UseSystemPasswordChar = false;
            this.rIdTaker.WordWrap = true;
            // 
            // label4
            // 
            this.label4.AutoSize = true;
            this.label4.Location = new System.Drawing.Point(352, 366);
            this.label4.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label4.Name = "label4";
            this.label4.Size = new System.Drawing.Size(83, 17);
            this.label4.TabIndex = 12;
            this.label4.Text = "Tên độc giả";
            // 
            // label5
            // 
            this.label5.AutoSize = true;
            this.label5.Location = new System.Drawing.Point(352, 420);
            this.label5.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label5.Name = "label5";
            this.label5.Size = new System.Drawing.Size(42, 17);
            this.label5.TabIndex = 12;
            this.label5.Text = "Email";
            // 
            // label6
            // 
            this.label6.AutoSize = true;
            this.label6.Location = new System.Drawing.Point(352, 475);
            this.label6.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label6.Name = "label6";
            this.label6.Size = new System.Drawing.Size(51, 17);
            this.label6.TabIndex = 12;
            this.label6.Text = "Địa chỉ";
            // 
            // label7
            // 
            this.label7.AutoSize = true;
            this.label7.Location = new System.Drawing.Point(352, 534);
            this.label7.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label7.Name = "label7";
            this.label7.Size = new System.Drawing.Size(71, 17);
            this.label7.TabIndex = 12;
            this.label7.Text = "Ngày sinh";
            // 
            // delBt
            // 
            this.delBt.AllowAnimations = true;
            this.delBt.AllowMouseEffects = true;
            this.delBt.AllowToggling = false;
            this.delBt.AnimationSpeed = 200;
            this.delBt.AutoGenerateColors = false;
            this.delBt.AutoRoundBorders = false;
            this.delBt.AutoSizeLeftIcon = true;
            this.delBt.AutoSizeRightIcon = true;
            this.delBt.BackColor = System.Drawing.Color.Transparent;
            this.delBt.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.delBt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("delBt.BackgroundImage")));
            this.delBt.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.delBt.ButtonText = "Xóa";
            this.delBt.ButtonTextMarginLeft = 0;
            this.delBt.ColorContrastOnClick = 45;
            this.delBt.ColorContrastOnHover = 45;
            this.delBt.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            this.delBt.CustomizableEdges = borderEdges3;
            this.delBt.DialogResult = System.Windows.Forms.DialogResult.None;
            this.delBt.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.delBt.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.delBt.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.delBt.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.delBt.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.delBt.ForeColor = System.Drawing.Color.White;
            this.delBt.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.delBt.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.delBt.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.delBt.IconMarginLeft = 11;
            this.delBt.IconPadding = 10;
            this.delBt.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.delBt.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.delBt.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.delBt.IconSize = 25;
            this.delBt.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.delBt.IdleBorderRadius = 1;
            this.delBt.IdleBorderThickness = 1;
            this.delBt.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.delBt.IdleIconLeftImage = null;
            this.delBt.IdleIconRightImage = null;
            this.delBt.IndicateFocus = false;
            this.delBt.Location = new System.Drawing.Point(1059, 511);
            this.delBt.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.delBt.Name = "delBt";
            this.delBt.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.delBt.OnDisabledState.BorderRadius = 1;
            this.delBt.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.delBt.OnDisabledState.BorderThickness = 1;
            this.delBt.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.delBt.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.delBt.OnDisabledState.IconLeftImage = null;
            this.delBt.OnDisabledState.IconRightImage = null;
            this.delBt.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.delBt.onHoverState.BorderRadius = 1;
            this.delBt.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.delBt.onHoverState.BorderThickness = 1;
            this.delBt.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.delBt.onHoverState.ForeColor = System.Drawing.Color.White;
            this.delBt.onHoverState.IconLeftImage = null;
            this.delBt.onHoverState.IconRightImage = null;
            this.delBt.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.delBt.OnIdleState.BorderRadius = 1;
            this.delBt.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.delBt.OnIdleState.BorderThickness = 1;
            this.delBt.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.delBt.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.delBt.OnIdleState.IconLeftImage = null;
            this.delBt.OnIdleState.IconRightImage = null;
            this.delBt.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.delBt.OnPressedState.BorderRadius = 1;
            this.delBt.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.delBt.OnPressedState.BorderThickness = 1;
            this.delBt.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.delBt.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.delBt.OnPressedState.IconLeftImage = null;
            this.delBt.OnPressedState.IconRightImage = null;
            this.delBt.Size = new System.Drawing.Size(149, 39);
            this.delBt.TabIndex = 13;
            this.delBt.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.delBt.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.delBt.TextMarginLeft = 0;
            this.delBt.TextPadding = new System.Windows.Forms.Padding(0);
            this.delBt.UseDefaultRadiusAndThickness = true;
            this.delBt.Click += new System.EventHandler(this.delBt_Click);
            // 
            // bookData
            // 
            this.bookData.AllowCustomTheming = false;
            this.bookData.AllowUserToAddRows = false;
            dataGridViewCellStyle1.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle1.ForeColor = System.Drawing.Color.Black;
            this.bookData.AlternatingRowsDefaultCellStyle = dataGridViewCellStyle1;
            this.bookData.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.bookData.BackgroundColor = System.Drawing.SystemColors.Control;
            this.bookData.BorderStyle = System.Windows.Forms.BorderStyle.None;
            this.bookData.CellBorderStyle = System.Windows.Forms.DataGridViewCellBorderStyle.SingleHorizontal;
            this.bookData.ColumnHeadersBorderStyle = System.Windows.Forms.DataGridViewHeaderBorderStyle.None;
            dataGridViewCellStyle2.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle2.BackColor = System.Drawing.Color.DodgerBlue;
            dataGridViewCellStyle2.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle2.ForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            dataGridViewCellStyle2.SelectionForeColor = System.Drawing.Color.White;
            dataGridViewCellStyle2.WrapMode = System.Windows.Forms.DataGridViewTriState.True;
            this.bookData.ColumnHeadersDefaultCellStyle = dataGridViewCellStyle2;
            this.bookData.ColumnHeadersHeight = 40;
            this.bookData.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.bID,
            this.bookName,
            this.status,
            this.price});
            this.bookData.CurrentTheme.AlternatingRowsStyle.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(248)))), ((int)(((byte)(251)))), ((int)(((byte)(255)))));
            this.bookData.CurrentTheme.AlternatingRowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bookData.CurrentTheme.AlternatingRowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bookData.CurrentTheme.AlternatingRowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bookData.CurrentTheme.AlternatingRowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            this.bookData.CurrentTheme.BackColor = System.Drawing.Color.White;
            this.bookData.CurrentTheme.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bookData.CurrentTheme.HeaderStyle.BackColor = System.Drawing.Color.DodgerBlue;
            this.bookData.CurrentTheme.HeaderStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 11.75F, System.Drawing.FontStyle.Bold);
            this.bookData.CurrentTheme.HeaderStyle.ForeColor = System.Drawing.Color.White;
            this.bookData.CurrentTheme.HeaderStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(24)))), ((int)(((byte)(115)))), ((int)(((byte)(204)))));
            this.bookData.CurrentTheme.HeaderStyle.SelectionForeColor = System.Drawing.Color.White;
            this.bookData.CurrentTheme.Name = null;
            this.bookData.CurrentTheme.RowsStyle.BackColor = System.Drawing.Color.White;
            this.bookData.CurrentTheme.RowsStyle.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            this.bookData.CurrentTheme.RowsStyle.ForeColor = System.Drawing.Color.Black;
            this.bookData.CurrentTheme.RowsStyle.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            this.bookData.CurrentTheme.RowsStyle.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.Alignment = System.Windows.Forms.DataGridViewContentAlignment.MiddleLeft;
            dataGridViewCellStyle3.BackColor = System.Drawing.Color.White;
            dataGridViewCellStyle3.Font = new System.Drawing.Font("Segoe UI Semibold", 9.75F, System.Drawing.FontStyle.Bold);
            dataGridViewCellStyle3.ForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.SelectionBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(210)))), ((int)(((byte)(232)))), ((int)(((byte)(255)))));
            dataGridViewCellStyle3.SelectionForeColor = System.Drawing.Color.Black;
            dataGridViewCellStyle3.WrapMode = System.Windows.Forms.DataGridViewTriState.False;
            this.bookData.DefaultCellStyle = dataGridViewCellStyle3;
            this.bookData.EnableHeadersVisualStyles = false;
            this.bookData.GridColor = System.Drawing.Color.FromArgb(((int)(((byte)(221)))), ((int)(((byte)(238)))), ((int)(((byte)(255)))));
            this.bookData.HeaderBackColor = System.Drawing.Color.DodgerBlue;
            this.bookData.HeaderBgColor = System.Drawing.Color.Empty;
            this.bookData.HeaderForeColor = System.Drawing.Color.White;
            this.bookData.Location = new System.Drawing.Point(-1, -1);
            this.bookData.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.bookData.Name = "bookData";
            this.bookData.RowHeadersVisible = false;
            this.bookData.RowHeadersWidth = 51;
            this.bookData.RowTemplate.Height = 40;
            this.bookData.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.bookData.Size = new System.Drawing.Size(1500, 235);
            this.bookData.TabIndex = 14;
            this.bookData.Theme = Bunifu.UI.WinForms.BunifuDataGridView.PresetThemes.Light;
            // 
            // bID
            // 
            this.bID.DividerWidth = 1;
            this.bID.HeaderText = "Mã sách";
            this.bID.MinimumWidth = 6;
            this.bID.Name = "bID";
            this.bID.ReadOnly = true;
            // 
            // bookName
            // 
            this.bookName.DividerWidth = 1;
            this.bookName.HeaderText = "Tên sách";
            this.bookName.MinimumWidth = 6;
            this.bookName.Name = "bookName";
            this.bookName.ReadOnly = true;
            // 
            // status
            // 
            this.status.DividerWidth = 1;
            this.status.HeaderText = "Trạng thái";
            this.status.MinimumWidth = 6;
            this.status.Name = "status";
            this.status.ReadOnly = true;
            // 
            // price
            // 
            this.price.DividerWidth = 1;
            this.price.HeaderText = "Trị giá";
            this.price.MinimumWidth = 6;
            this.price.Name = "price";
            this.price.ReadOnly = true;
            // 
            // IssuedBooks
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1500, 650);
            this.Controls.Add(this.bookData);
            this.Controls.Add(this.delBt);
            this.Controls.Add(this.label7);
            this.Controls.Add(this.label6);
            this.Controls.Add(this.label5);
            this.Controls.Add(this.label4);
            this.Controls.Add(this.label3);
            this.Controls.Add(this.label2);
            this.Controls.Add(this.bSearchBt);
            this.Controls.Add(this.rSearchBt);
            this.Controls.Add(this.addBookBt);
            this.Controls.Add(this.saveBt);
            this.Controls.Add(this.dateGetter);
            this.Controls.Add(this.label1);
            this.Controls.Add(this.rBirth);
            this.Controls.Add(this.rEmail);
            this.Controls.Add(this.rAddress);
            this.Controls.Add(this.rName);
            this.Controls.Add(this.nameBook);
            this.Controls.Add(this.bIdTaker);
            this.Controls.Add(this.rIdTaker);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.Name = "IssuedBooks";
            ((System.ComponentModel.ISupportInitialize)(this.bookData)).EndInit();
            this.ResumeLayout(false);
            this.PerformLayout();

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuTextBox rIdTaker;
        private Bunifu.UI.WinForms.BunifuTextBox rName;
        private Bunifu.UI.WinForms.BunifuTextBox rAddress;
        private Bunifu.UI.WinForms.BunifuTextBox rEmail;
        private Bunifu.UI.WinForms.BunifuTextBox rBirth;
        private System.Windows.Forms.Label label1;
        private Bunifu.UI.WinForms.BunifuTextBox bIdTaker;
        private Bunifu.UI.WinForms.BunifuDatePicker dateGetter;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton saveBt;
        private Bunifu.UI.WinForms.BunifuTextBox nameBook;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton addBookBt;
        private Bunifu.UI.WinForms.BunifuImageButton rSearchBt;
        private Bunifu.UI.WinForms.BunifuImageButton bSearchBt;
        private System.Windows.Forms.Label label2;
        private System.Windows.Forms.Label label3;
        private System.Windows.Forms.Label label4;
        private System.Windows.Forms.Label label5;
        private System.Windows.Forms.Label label6;
        private System.Windows.Forms.Label label7;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton delBt;
        private Bunifu.UI.WinForms.BunifuDataGridView bookData;
        private System.Windows.Forms.DataGridViewTextBoxColumn bID;
        private System.Windows.Forms.DataGridViewTextBoxColumn bookName;
        private System.Windows.Forms.DataGridViewTextBoxColumn status;
        private System.Windows.Forms.DataGridViewTextBoxColumn price;
    }
}