
namespace LibraryApp
{
    partial class ModifyBookScreen
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            this.components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(ModifyBookScreen));
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties37 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties38 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties39 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties40 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties41 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties42 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties43 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties44 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties45 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties46 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties47 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties48 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties49 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties50 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties51 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties52 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties53 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties54 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties55 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties56 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties57 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties58 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties59 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties60 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties61 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties62 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties63 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties64 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties65 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties66 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties67 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties68 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties69 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties70 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties71 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            Bunifu.UI.WinForms.BunifuTextBox.StateProperties stateProperties72 = new Bunifu.UI.WinForms.BunifuTextBox.StateProperties();
            this.priceTaker = new Bunifu.UI.WinForms.BunifuTextBox();
            this.topPanel = new System.Windows.Forms.Panel();
            this.exitButton = new Bunifu.UI.WinForms.BunifuImageButton();
            this.label1 = new System.Windows.Forms.Label();
            this.bunifuDragControl1 = new Bunifu.Framework.UI.BunifuDragControl(this.components);
            this.saveBt = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            this.statusTaker = new Bunifu.UI.WinForms.BunifuTextBox();
            this.amountTaker = new Bunifu.UI.WinForms.BunifuTextBox();
            this.publisherTaker = new Bunifu.UI.WinForms.BunifuTextBox();
            this.publishYearTaker = new Bunifu.UI.WinForms.BunifuTextBox();
            this.posTaker = new Bunifu.UI.WinForms.BunifuTextBox();
            this.authorTaker = new Bunifu.UI.WinForms.BunifuTextBox();
            this.genreTaker = new Bunifu.UI.WinForms.BunifuTextBox();
            this.nameTaker = new Bunifu.UI.WinForms.BunifuTextBox();
            this.topPanel.SuspendLayout();
            this.SuspendLayout();
            // 
            // priceTaker
            // 
            this.priceTaker.AcceptsReturn = false;
            this.priceTaker.AcceptsTab = false;
            this.priceTaker.AnimationSpeed = 200;
            this.priceTaker.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.priceTaker.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.priceTaker.BackColor = System.Drawing.Color.White;
            this.priceTaker.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("priceTaker.BackgroundImage")));
            this.priceTaker.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.priceTaker.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.priceTaker.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.priceTaker.BorderColorIdle = System.Drawing.Color.Silver;
            this.priceTaker.BorderRadius = 1;
            this.priceTaker.BorderThickness = 1;
            this.priceTaker.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.priceTaker.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.priceTaker.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.priceTaker.DefaultText = "";
            this.priceTaker.FillColor = System.Drawing.Color.White;
            this.priceTaker.HideSelection = true;
            this.priceTaker.IconLeft = null;
            this.priceTaker.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.priceTaker.IconPadding = 10;
            this.priceTaker.IconRight = null;
            this.priceTaker.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.priceTaker.Lines = new string[0];
            this.priceTaker.Location = new System.Drawing.Point(519, 382);
            this.priceTaker.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.priceTaker.MaxLength = 32767;
            this.priceTaker.MinimumSize = new System.Drawing.Size(1, 1);
            this.priceTaker.Modified = false;
            this.priceTaker.Multiline = false;
            this.priceTaker.Name = "priceTaker";
            stateProperties37.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties37.FillColor = System.Drawing.Color.Empty;
            stateProperties37.ForeColor = System.Drawing.Color.Empty;
            stateProperties37.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.priceTaker.OnActiveState = stateProperties37;
            stateProperties38.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties38.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties38.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties38.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.priceTaker.OnDisabledState = stateProperties38;
            stateProperties39.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties39.FillColor = System.Drawing.Color.Empty;
            stateProperties39.ForeColor = System.Drawing.Color.Empty;
            stateProperties39.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.priceTaker.OnHoverState = stateProperties39;
            stateProperties40.BorderColor = System.Drawing.Color.Silver;
            stateProperties40.FillColor = System.Drawing.Color.White;
            stateProperties40.ForeColor = System.Drawing.Color.Empty;
            stateProperties40.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.priceTaker.OnIdleState = stateProperties40;
            this.priceTaker.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.priceTaker.PasswordChar = '\0';
            this.priceTaker.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.priceTaker.PlaceholderText = "Price";
            this.priceTaker.ReadOnly = false;
            this.priceTaker.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.priceTaker.SelectedText = "";
            this.priceTaker.SelectionLength = 0;
            this.priceTaker.SelectionStart = 0;
            this.priceTaker.ShortcutsEnabled = true;
            this.priceTaker.Size = new System.Drawing.Size(347, 46);
            this.priceTaker.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.priceTaker.TabIndex = 12;
            this.priceTaker.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.priceTaker.TextMarginBottom = 0;
            this.priceTaker.TextMarginLeft = 3;
            this.priceTaker.TextMarginTop = 0;
            this.priceTaker.TextPlaceholder = "Price";
            this.priceTaker.UseSystemPasswordChar = false;
            this.priceTaker.WordWrap = true;
            // 
            // topPanel
            // 
            this.topPanel.BackColor = System.Drawing.SystemColors.ActiveCaptionText;
            this.topPanel.Controls.Add(this.exitButton);
            this.topPanel.Controls.Add(this.label1);
            this.topPanel.Dock = System.Windows.Forms.DockStyle.Top;
            this.topPanel.Location = new System.Drawing.Point(0, 0);
            this.topPanel.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.topPanel.Name = "topPanel";
            this.topPanel.Size = new System.Drawing.Size(993, 105);
            this.topPanel.TabIndex = 8;
            // 
            // exitButton
            // 
            this.exitButton.ActiveImage = null;
            this.exitButton.AllowAnimations = true;
            this.exitButton.AllowBuffering = false;
            this.exitButton.AllowToggling = false;
            this.exitButton.AllowZooming = true;
            this.exitButton.AllowZoomingOnFocus = false;
            this.exitButton.BackColor = System.Drawing.Color.Transparent;
            this.exitButton.DialogResult = System.Windows.Forms.DialogResult.None;
            this.exitButton.ErrorImage = ((System.Drawing.Image)(resources.GetObject("exitButton.ErrorImage")));
            this.exitButton.FadeWhenInactive = false;
            this.exitButton.Flip = Bunifu.UI.WinForms.BunifuImageButton.FlipOrientation.Normal;
            this.exitButton.Image = global::LibraryApp.Properties.Resources.exit;
            this.exitButton.ImageActive = null;
            this.exitButton.ImageLocation = null;
            this.exitButton.ImageMargin = 5;
            this.exitButton.ImageSize = new System.Drawing.Size(39, 33);
            this.exitButton.ImageZoomSize = new System.Drawing.Size(44, 38);
            this.exitButton.InitialImage = ((System.Drawing.Image)(resources.GetObject("exitButton.InitialImage")));
            this.exitButton.Location = new System.Drawing.Point(883, 23);
            this.exitButton.Margin = new System.Windows.Forms.Padding(3, 2, 3, 2);
            this.exitButton.Name = "exitButton";
            this.exitButton.Rotation = 0;
            this.exitButton.ShowActiveImage = true;
            this.exitButton.ShowCursorChanges = true;
            this.exitButton.ShowImageBorders = true;
            this.exitButton.ShowSizeMarkers = false;
            this.exitButton.Size = new System.Drawing.Size(44, 38);
            this.exitButton.TabIndex = 2;
            this.exitButton.ToolTipText = "";
            this.exitButton.WaitOnLoad = false;
            this.exitButton.Zoom = 5;
            this.exitButton.ZoomSpeed = 10;
            this.exitButton.Click += new System.EventHandler(this.exitButton_Click);
            // 
            // label1
            // 
            this.label1.AutoSize = true;
            this.label1.Font = new System.Drawing.Font("Microsoft Sans Serif", 14.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
            this.label1.ForeColor = System.Drawing.SystemColors.ButtonHighlight;
            this.label1.Location = new System.Drawing.Point(17, 32);
            this.label1.Margin = new System.Windows.Forms.Padding(4, 0, 4, 0);
            this.label1.Name = "label1";
            this.label1.Size = new System.Drawing.Size(263, 29);
            this.label1.TabIndex = 0;
            this.label1.Text = "Modify Book Infomation";
            // 
            // bunifuDragControl1
            // 
            this.bunifuDragControl1.Fixed = true;
            this.bunifuDragControl1.Horizontal = true;
            this.bunifuDragControl1.TargetControl = this.topPanel;
            this.bunifuDragControl1.Vertical = true;
            // 
            // saveBt
            // 
            this.saveBt.AllowAnimations = true;
            this.saveBt.AllowMouseEffects = true;
            this.saveBt.AllowToggling = false;
            this.saveBt.AnimationSpeed = 200;
            this.saveBt.AutoGenerateColors = false;
            this.saveBt.AutoRoundBorders = false;
            this.saveBt.AutoSizeLeftIcon = true;
            this.saveBt.AutoSizeRightIcon = true;
            this.saveBt.BackColor = System.Drawing.Color.Transparent;
            this.saveBt.BackColor1 = System.Drawing.Color.DodgerBlue;
            this.saveBt.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("saveBt.BackgroundImage")));
            this.saveBt.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.saveBt.ButtonText = "save";
            this.saveBt.ButtonTextMarginLeft = 0;
            this.saveBt.ColorContrastOnClick = 45;
            this.saveBt.ColorContrastOnHover = 45;
            this.saveBt.Cursor = System.Windows.Forms.Cursors.Default;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            this.saveBt.CustomizableEdges = borderEdges2;
            this.saveBt.DialogResult = System.Windows.Forms.DialogResult.None;
            this.saveBt.DisabledBorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.saveBt.DisabledFillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.saveBt.DisabledForecolor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.saveBt.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            this.saveBt.Font = new System.Drawing.Font("Segoe UI", 9F);
            this.saveBt.ForeColor = System.Drawing.Color.White;
            this.saveBt.IconLeftAlign = System.Drawing.ContentAlignment.MiddleLeft;
            this.saveBt.IconLeftCursor = System.Windows.Forms.Cursors.Default;
            this.saveBt.IconLeftPadding = new System.Windows.Forms.Padding(11, 3, 3, 3);
            this.saveBt.IconMarginLeft = 11;
            this.saveBt.IconPadding = 10;
            this.saveBt.IconRightAlign = System.Drawing.ContentAlignment.MiddleRight;
            this.saveBt.IconRightCursor = System.Windows.Forms.Cursors.Default;
            this.saveBt.IconRightPadding = new System.Windows.Forms.Padding(3, 3, 7, 3);
            this.saveBt.IconSize = 25;
            this.saveBt.IdleBorderColor = System.Drawing.Color.DodgerBlue;
            this.saveBt.IdleBorderRadius = 1;
            this.saveBt.IdleBorderThickness = 1;
            this.saveBt.IdleFillColor = System.Drawing.Color.DodgerBlue;
            this.saveBt.IdleIconLeftImage = null;
            this.saveBt.IdleIconRightImage = null;
            this.saveBt.IndicateFocus = false;
            this.saveBt.Location = new System.Drawing.Point(799, 508);
            this.saveBt.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.saveBt.Name = "saveBt";
            this.saveBt.OnDisabledState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(191)))), ((int)(((byte)(191)))), ((int)(((byte)(191)))));
            this.saveBt.OnDisabledState.BorderRadius = 1;
            this.saveBt.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.saveBt.OnDisabledState.BorderThickness = 1;
            this.saveBt.OnDisabledState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.saveBt.OnDisabledState.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(168)))), ((int)(((byte)(160)))), ((int)(((byte)(168)))));
            this.saveBt.OnDisabledState.IconLeftImage = null;
            this.saveBt.OnDisabledState.IconRightImage = null;
            this.saveBt.onHoverState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.saveBt.onHoverState.BorderRadius = 1;
            this.saveBt.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.saveBt.onHoverState.BorderThickness = 1;
            this.saveBt.onHoverState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.saveBt.onHoverState.ForeColor = System.Drawing.Color.White;
            this.saveBt.onHoverState.IconLeftImage = null;
            this.saveBt.onHoverState.IconRightImage = null;
            this.saveBt.OnIdleState.BorderColor = System.Drawing.Color.DodgerBlue;
            this.saveBt.OnIdleState.BorderRadius = 1;
            this.saveBt.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.saveBt.OnIdleState.BorderThickness = 1;
            this.saveBt.OnIdleState.FillColor = System.Drawing.Color.DodgerBlue;
            this.saveBt.OnIdleState.ForeColor = System.Drawing.Color.White;
            this.saveBt.OnIdleState.IconLeftImage = null;
            this.saveBt.OnIdleState.IconRightImage = null;
            this.saveBt.OnPressedState.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.saveBt.OnPressedState.BorderRadius = 1;
            this.saveBt.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            this.saveBt.OnPressedState.BorderThickness = 1;
            this.saveBt.OnPressedState.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(40)))), ((int)(((byte)(96)))), ((int)(((byte)(144)))));
            this.saveBt.OnPressedState.ForeColor = System.Drawing.Color.White;
            this.saveBt.OnPressedState.IconLeftImage = null;
            this.saveBt.OnPressedState.IconRightImage = null;
            this.saveBt.Size = new System.Drawing.Size(128, 32);
            this.saveBt.TabIndex = 18;
            this.saveBt.TextAlign = System.Drawing.ContentAlignment.MiddleCenter;
            this.saveBt.TextAlignment = System.Windows.Forms.HorizontalAlignment.Center;
            this.saveBt.TextMarginLeft = 0;
            this.saveBt.TextPadding = new System.Windows.Forms.Padding(0);
            this.saveBt.UseDefaultRadiusAndThickness = true;
            // 
            // statusTaker
            // 
            this.statusTaker.AcceptsReturn = false;
            this.statusTaker.AcceptsTab = false;
            this.statusTaker.AnimationSpeed = 200;
            this.statusTaker.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.statusTaker.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.statusTaker.BackColor = System.Drawing.Color.White;
            this.statusTaker.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("statusTaker.BackgroundImage")));
            this.statusTaker.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.statusTaker.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.statusTaker.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.statusTaker.BorderColorIdle = System.Drawing.Color.Silver;
            this.statusTaker.BorderRadius = 1;
            this.statusTaker.BorderThickness = 1;
            this.statusTaker.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.statusTaker.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.statusTaker.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.statusTaker.DefaultText = "";
            this.statusTaker.FillColor = System.Drawing.Color.White;
            this.statusTaker.HideSelection = true;
            this.statusTaker.IconLeft = null;
            this.statusTaker.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.statusTaker.IconPadding = 10;
            this.statusTaker.IconRight = null;
            this.statusTaker.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.statusTaker.Lines = new string[0];
            this.statusTaker.Location = new System.Drawing.Point(83, 446);
            this.statusTaker.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.statusTaker.MaxLength = 32767;
            this.statusTaker.MinimumSize = new System.Drawing.Size(1, 1);
            this.statusTaker.Modified = false;
            this.statusTaker.Multiline = false;
            this.statusTaker.Name = "statusTaker";
            stateProperties41.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties41.FillColor = System.Drawing.Color.Empty;
            stateProperties41.ForeColor = System.Drawing.Color.Empty;
            stateProperties41.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.statusTaker.OnActiveState = stateProperties41;
            stateProperties42.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties42.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties42.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties42.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.statusTaker.OnDisabledState = stateProperties42;
            stateProperties43.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties43.FillColor = System.Drawing.Color.Empty;
            stateProperties43.ForeColor = System.Drawing.Color.Empty;
            stateProperties43.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.statusTaker.OnHoverState = stateProperties43;
            stateProperties44.BorderColor = System.Drawing.Color.Silver;
            stateProperties44.FillColor = System.Drawing.Color.White;
            stateProperties44.ForeColor = System.Drawing.Color.Empty;
            stateProperties44.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.statusTaker.OnIdleState = stateProperties44;
            this.statusTaker.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.statusTaker.PasswordChar = '\0';
            this.statusTaker.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.statusTaker.PlaceholderText = "Status";
            this.statusTaker.ReadOnly = false;
            this.statusTaker.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.statusTaker.SelectedText = "";
            this.statusTaker.SelectionLength = 0;
            this.statusTaker.SelectionStart = 0;
            this.statusTaker.ShortcutsEnabled = true;
            this.statusTaker.Size = new System.Drawing.Size(347, 46);
            this.statusTaker.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.statusTaker.TabIndex = 16;
            this.statusTaker.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.statusTaker.TextMarginBottom = 0;
            this.statusTaker.TextMarginLeft = 3;
            this.statusTaker.TextMarginTop = 0;
            this.statusTaker.TextPlaceholder = "Status";
            this.statusTaker.UseSystemPasswordChar = false;
            this.statusTaker.WordWrap = true;
            // 
            // amountTaker
            // 
            this.amountTaker.AcceptsReturn = false;
            this.amountTaker.AcceptsTab = false;
            this.amountTaker.AnimationSpeed = 200;
            this.amountTaker.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.amountTaker.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.amountTaker.BackColor = System.Drawing.Color.White;
            this.amountTaker.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("amountTaker.BackgroundImage")));
            this.amountTaker.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.amountTaker.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.amountTaker.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.amountTaker.BorderColorIdle = System.Drawing.Color.Silver;
            this.amountTaker.BorderRadius = 1;
            this.amountTaker.BorderThickness = 1;
            this.amountTaker.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.amountTaker.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.amountTaker.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.amountTaker.DefaultText = "";
            this.amountTaker.FillColor = System.Drawing.Color.White;
            this.amountTaker.HideSelection = true;
            this.amountTaker.IconLeft = null;
            this.amountTaker.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.amountTaker.IconPadding = 10;
            this.amountTaker.IconRight = null;
            this.amountTaker.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.amountTaker.Lines = new string[0];
            this.amountTaker.Location = new System.Drawing.Point(519, 190);
            this.amountTaker.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.amountTaker.MaxLength = 32767;
            this.amountTaker.MinimumSize = new System.Drawing.Size(1, 1);
            this.amountTaker.Modified = false;
            this.amountTaker.Multiline = false;
            this.amountTaker.Name = "amountTaker";
            stateProperties45.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties45.FillColor = System.Drawing.Color.Empty;
            stateProperties45.ForeColor = System.Drawing.Color.Empty;
            stateProperties45.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.amountTaker.OnActiveState = stateProperties45;
            stateProperties46.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties46.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties46.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties46.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.amountTaker.OnDisabledState = stateProperties46;
            stateProperties47.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties47.FillColor = System.Drawing.Color.Empty;
            stateProperties47.ForeColor = System.Drawing.Color.Empty;
            stateProperties47.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.amountTaker.OnHoverState = stateProperties47;
            stateProperties48.BorderColor = System.Drawing.Color.Silver;
            stateProperties48.FillColor = System.Drawing.Color.White;
            stateProperties48.ForeColor = System.Drawing.Color.Empty;
            stateProperties48.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.amountTaker.OnIdleState = stateProperties48;
            this.amountTaker.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.amountTaker.PasswordChar = '\0';
            this.amountTaker.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.amountTaker.PlaceholderText = "Amount";
            this.amountTaker.ReadOnly = false;
            this.amountTaker.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.amountTaker.SelectedText = "";
            this.amountTaker.SelectionLength = 0;
            this.amountTaker.SelectionStart = 0;
            this.amountTaker.ShortcutsEnabled = true;
            this.amountTaker.Size = new System.Drawing.Size(347, 46);
            this.amountTaker.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.amountTaker.TabIndex = 17;
            this.amountTaker.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.amountTaker.TextMarginBottom = 0;
            this.amountTaker.TextMarginLeft = 3;
            this.amountTaker.TextMarginTop = 0;
            this.amountTaker.TextPlaceholder = "Amount";
            this.amountTaker.UseSystemPasswordChar = false;
            this.amountTaker.WordWrap = true;
            // 
            // publisherTaker
            // 
            this.publisherTaker.AcceptsReturn = false;
            this.publisherTaker.AcceptsTab = false;
            this.publisherTaker.AnimationSpeed = 200;
            this.publisherTaker.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.publisherTaker.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.publisherTaker.BackColor = System.Drawing.Color.White;
            this.publisherTaker.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("publisherTaker.BackgroundImage")));
            this.publisherTaker.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.publisherTaker.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.publisherTaker.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.publisherTaker.BorderColorIdle = System.Drawing.Color.Silver;
            this.publisherTaker.BorderRadius = 1;
            this.publisherTaker.BorderThickness = 1;
            this.publisherTaker.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.publisherTaker.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.publisherTaker.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.publisherTaker.DefaultText = "";
            this.publisherTaker.FillColor = System.Drawing.Color.White;
            this.publisherTaker.HideSelection = true;
            this.publisherTaker.IconLeft = null;
            this.publisherTaker.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.publisherTaker.IconPadding = 10;
            this.publisherTaker.IconRight = null;
            this.publisherTaker.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.publisherTaker.Lines = new string[0];
            this.publisherTaker.Location = new System.Drawing.Point(83, 382);
            this.publisherTaker.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.publisherTaker.MaxLength = 32767;
            this.publisherTaker.MinimumSize = new System.Drawing.Size(1, 1);
            this.publisherTaker.Modified = false;
            this.publisherTaker.Multiline = false;
            this.publisherTaker.Name = "publisherTaker";
            stateProperties49.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties49.FillColor = System.Drawing.Color.Empty;
            stateProperties49.ForeColor = System.Drawing.Color.Empty;
            stateProperties49.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.publisherTaker.OnActiveState = stateProperties49;
            stateProperties50.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties50.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties50.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties50.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.publisherTaker.OnDisabledState = stateProperties50;
            stateProperties51.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties51.FillColor = System.Drawing.Color.Empty;
            stateProperties51.ForeColor = System.Drawing.Color.Empty;
            stateProperties51.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.publisherTaker.OnHoverState = stateProperties51;
            stateProperties52.BorderColor = System.Drawing.Color.Silver;
            stateProperties52.FillColor = System.Drawing.Color.White;
            stateProperties52.ForeColor = System.Drawing.Color.Empty;
            stateProperties52.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.publisherTaker.OnIdleState = stateProperties52;
            this.publisherTaker.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.publisherTaker.PasswordChar = '\0';
            this.publisherTaker.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.publisherTaker.PlaceholderText = "Publisher";
            this.publisherTaker.ReadOnly = false;
            this.publisherTaker.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.publisherTaker.SelectedText = "";
            this.publisherTaker.SelectionLength = 0;
            this.publisherTaker.SelectionStart = 0;
            this.publisherTaker.ShortcutsEnabled = true;
            this.publisherTaker.Size = new System.Drawing.Size(347, 46);
            this.publisherTaker.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.publisherTaker.TabIndex = 13;
            this.publisherTaker.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.publisherTaker.TextMarginBottom = 0;
            this.publisherTaker.TextMarginLeft = 3;
            this.publisherTaker.TextMarginTop = 0;
            this.publisherTaker.TextPlaceholder = "Publisher";
            this.publisherTaker.UseSystemPasswordChar = false;
            this.publisherTaker.WordWrap = true;
            // 
            // publishYearTaker
            // 
            this.publishYearTaker.AcceptsReturn = false;
            this.publishYearTaker.AcceptsTab = false;
            this.publishYearTaker.AnimationSpeed = 200;
            this.publishYearTaker.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.publishYearTaker.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.publishYearTaker.BackColor = System.Drawing.Color.White;
            this.publishYearTaker.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("publishYearTaker.BackgroundImage")));
            this.publishYearTaker.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.publishYearTaker.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.publishYearTaker.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.publishYearTaker.BorderColorIdle = System.Drawing.Color.Silver;
            this.publishYearTaker.BorderRadius = 1;
            this.publishYearTaker.BorderThickness = 1;
            this.publishYearTaker.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.publishYearTaker.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.publishYearTaker.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.publishYearTaker.DefaultText = "";
            this.publishYearTaker.FillColor = System.Drawing.Color.White;
            this.publishYearTaker.HideSelection = true;
            this.publishYearTaker.IconLeft = null;
            this.publishYearTaker.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.publishYearTaker.IconPadding = 10;
            this.publishYearTaker.IconRight = null;
            this.publishYearTaker.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.publishYearTaker.Lines = new string[0];
            this.publishYearTaker.Location = new System.Drawing.Point(519, 318);
            this.publishYearTaker.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.publishYearTaker.MaxLength = 32767;
            this.publishYearTaker.MinimumSize = new System.Drawing.Size(1, 1);
            this.publishYearTaker.Modified = false;
            this.publishYearTaker.Multiline = false;
            this.publishYearTaker.Name = "publishYearTaker";
            stateProperties53.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties53.FillColor = System.Drawing.Color.Empty;
            stateProperties53.ForeColor = System.Drawing.Color.Empty;
            stateProperties53.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.publishYearTaker.OnActiveState = stateProperties53;
            stateProperties54.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties54.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties54.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties54.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.publishYearTaker.OnDisabledState = stateProperties54;
            stateProperties55.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties55.FillColor = System.Drawing.Color.Empty;
            stateProperties55.ForeColor = System.Drawing.Color.Empty;
            stateProperties55.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.publishYearTaker.OnHoverState = stateProperties55;
            stateProperties56.BorderColor = System.Drawing.Color.Silver;
            stateProperties56.FillColor = System.Drawing.Color.White;
            stateProperties56.ForeColor = System.Drawing.Color.Empty;
            stateProperties56.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.publishYearTaker.OnIdleState = stateProperties56;
            this.publishYearTaker.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.publishYearTaker.PasswordChar = '\0';
            this.publishYearTaker.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.publishYearTaker.PlaceholderText = "Publish year";
            this.publishYearTaker.ReadOnly = false;
            this.publishYearTaker.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.publishYearTaker.SelectedText = "";
            this.publishYearTaker.SelectionLength = 0;
            this.publishYearTaker.SelectionStart = 0;
            this.publishYearTaker.ShortcutsEnabled = true;
            this.publishYearTaker.Size = new System.Drawing.Size(347, 46);
            this.publishYearTaker.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.publishYearTaker.TabIndex = 14;
            this.publishYearTaker.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.publishYearTaker.TextMarginBottom = 0;
            this.publishYearTaker.TextMarginLeft = 3;
            this.publishYearTaker.TextMarginTop = 0;
            this.publishYearTaker.TextPlaceholder = "Publish year";
            this.publishYearTaker.UseSystemPasswordChar = false;
            this.publishYearTaker.WordWrap = true;
            // 
            // posTaker
            // 
            this.posTaker.AcceptsReturn = false;
            this.posTaker.AcceptsTab = false;
            this.posTaker.AnimationSpeed = 200;
            this.posTaker.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.posTaker.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.posTaker.BackColor = System.Drawing.Color.White;
            this.posTaker.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("posTaker.BackgroundImage")));
            this.posTaker.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.posTaker.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.posTaker.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.posTaker.BorderColorIdle = System.Drawing.Color.Silver;
            this.posTaker.BorderRadius = 1;
            this.posTaker.BorderThickness = 1;
            this.posTaker.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.posTaker.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.posTaker.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.posTaker.DefaultText = "";
            this.posTaker.FillColor = System.Drawing.Color.White;
            this.posTaker.HideSelection = true;
            this.posTaker.IconLeft = null;
            this.posTaker.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.posTaker.IconPadding = 10;
            this.posTaker.IconRight = null;
            this.posTaker.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.posTaker.Lines = new string[0];
            this.posTaker.Location = new System.Drawing.Point(519, 254);
            this.posTaker.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.posTaker.MaxLength = 32767;
            this.posTaker.MinimumSize = new System.Drawing.Size(1, 1);
            this.posTaker.Modified = false;
            this.posTaker.Multiline = false;
            this.posTaker.Name = "posTaker";
            stateProperties57.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties57.FillColor = System.Drawing.Color.Empty;
            stateProperties57.ForeColor = System.Drawing.Color.Empty;
            stateProperties57.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.posTaker.OnActiveState = stateProperties57;
            stateProperties58.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties58.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties58.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties58.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.posTaker.OnDisabledState = stateProperties58;
            stateProperties59.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties59.FillColor = System.Drawing.Color.Empty;
            stateProperties59.ForeColor = System.Drawing.Color.Empty;
            stateProperties59.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.posTaker.OnHoverState = stateProperties59;
            stateProperties60.BorderColor = System.Drawing.Color.Silver;
            stateProperties60.FillColor = System.Drawing.Color.White;
            stateProperties60.ForeColor = System.Drawing.Color.Empty;
            stateProperties60.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.posTaker.OnIdleState = stateProperties60;
            this.posTaker.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.posTaker.PasswordChar = '\0';
            this.posTaker.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.posTaker.PlaceholderText = "Position";
            this.posTaker.ReadOnly = false;
            this.posTaker.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.posTaker.SelectedText = "";
            this.posTaker.SelectionLength = 0;
            this.posTaker.SelectionStart = 0;
            this.posTaker.ShortcutsEnabled = true;
            this.posTaker.Size = new System.Drawing.Size(347, 46);
            this.posTaker.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.posTaker.TabIndex = 15;
            this.posTaker.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.posTaker.TextMarginBottom = 0;
            this.posTaker.TextMarginLeft = 3;
            this.posTaker.TextMarginTop = 0;
            this.posTaker.TextPlaceholder = "Position";
            this.posTaker.UseSystemPasswordChar = false;
            this.posTaker.WordWrap = true;
            // 
            // authorTaker
            // 
            this.authorTaker.AcceptsReturn = false;
            this.authorTaker.AcceptsTab = false;
            this.authorTaker.AnimationSpeed = 200;
            this.authorTaker.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.authorTaker.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.authorTaker.BackColor = System.Drawing.Color.White;
            this.authorTaker.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("authorTaker.BackgroundImage")));
            this.authorTaker.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.authorTaker.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.authorTaker.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.authorTaker.BorderColorIdle = System.Drawing.Color.Silver;
            this.authorTaker.BorderRadius = 1;
            this.authorTaker.BorderThickness = 1;
            this.authorTaker.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.authorTaker.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.authorTaker.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.authorTaker.DefaultText = "";
            this.authorTaker.FillColor = System.Drawing.Color.White;
            this.authorTaker.HideSelection = true;
            this.authorTaker.IconLeft = null;
            this.authorTaker.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.authorTaker.IconPadding = 10;
            this.authorTaker.IconRight = null;
            this.authorTaker.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.authorTaker.Lines = new string[0];
            this.authorTaker.Location = new System.Drawing.Point(83, 254);
            this.authorTaker.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.authorTaker.MaxLength = 32767;
            this.authorTaker.MinimumSize = new System.Drawing.Size(1, 1);
            this.authorTaker.Modified = false;
            this.authorTaker.Multiline = false;
            this.authorTaker.Name = "authorTaker";
            stateProperties61.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties61.FillColor = System.Drawing.Color.Empty;
            stateProperties61.ForeColor = System.Drawing.Color.Empty;
            stateProperties61.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.authorTaker.OnActiveState = stateProperties61;
            stateProperties62.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties62.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties62.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties62.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.authorTaker.OnDisabledState = stateProperties62;
            stateProperties63.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties63.FillColor = System.Drawing.Color.Empty;
            stateProperties63.ForeColor = System.Drawing.Color.Empty;
            stateProperties63.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.authorTaker.OnHoverState = stateProperties63;
            stateProperties64.BorderColor = System.Drawing.Color.Silver;
            stateProperties64.FillColor = System.Drawing.Color.White;
            stateProperties64.ForeColor = System.Drawing.Color.Empty;
            stateProperties64.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.authorTaker.OnIdleState = stateProperties64;
            this.authorTaker.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.authorTaker.PasswordChar = '\0';
            this.authorTaker.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.authorTaker.PlaceholderText = "Author";
            this.authorTaker.ReadOnly = false;
            this.authorTaker.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.authorTaker.SelectedText = "";
            this.authorTaker.SelectionLength = 0;
            this.authorTaker.SelectionStart = 0;
            this.authorTaker.ShortcutsEnabled = true;
            this.authorTaker.Size = new System.Drawing.Size(347, 46);
            this.authorTaker.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.authorTaker.TabIndex = 10;
            this.authorTaker.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.authorTaker.TextMarginBottom = 0;
            this.authorTaker.TextMarginLeft = 3;
            this.authorTaker.TextMarginTop = 0;
            this.authorTaker.TextPlaceholder = "Author";
            this.authorTaker.UseSystemPasswordChar = false;
            this.authorTaker.WordWrap = true;
            // 
            // genreTaker
            // 
            this.genreTaker.AcceptsReturn = false;
            this.genreTaker.AcceptsTab = false;
            this.genreTaker.AnimationSpeed = 200;
            this.genreTaker.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.genreTaker.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.genreTaker.BackColor = System.Drawing.Color.White;
            this.genreTaker.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("genreTaker.BackgroundImage")));
            this.genreTaker.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.genreTaker.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.genreTaker.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.genreTaker.BorderColorIdle = System.Drawing.Color.Silver;
            this.genreTaker.BorderRadius = 1;
            this.genreTaker.BorderThickness = 1;
            this.genreTaker.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.genreTaker.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.genreTaker.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.genreTaker.DefaultText = "";
            this.genreTaker.FillColor = System.Drawing.Color.White;
            this.genreTaker.HideSelection = true;
            this.genreTaker.IconLeft = null;
            this.genreTaker.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.genreTaker.IconPadding = 10;
            this.genreTaker.IconRight = null;
            this.genreTaker.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.genreTaker.Lines = new string[0];
            this.genreTaker.Location = new System.Drawing.Point(83, 318);
            this.genreTaker.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.genreTaker.MaxLength = 32767;
            this.genreTaker.MinimumSize = new System.Drawing.Size(1, 1);
            this.genreTaker.Modified = false;
            this.genreTaker.Multiline = false;
            this.genreTaker.Name = "genreTaker";
            stateProperties65.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties65.FillColor = System.Drawing.Color.Empty;
            stateProperties65.ForeColor = System.Drawing.Color.Empty;
            stateProperties65.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.genreTaker.OnActiveState = stateProperties65;
            stateProperties66.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties66.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties66.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties66.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.genreTaker.OnDisabledState = stateProperties66;
            stateProperties67.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties67.FillColor = System.Drawing.Color.Empty;
            stateProperties67.ForeColor = System.Drawing.Color.Empty;
            stateProperties67.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.genreTaker.OnHoverState = stateProperties67;
            stateProperties68.BorderColor = System.Drawing.Color.Silver;
            stateProperties68.FillColor = System.Drawing.Color.White;
            stateProperties68.ForeColor = System.Drawing.Color.Empty;
            stateProperties68.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.genreTaker.OnIdleState = stateProperties68;
            this.genreTaker.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.genreTaker.PasswordChar = '\0';
            this.genreTaker.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.genreTaker.PlaceholderText = "Genre";
            this.genreTaker.ReadOnly = false;
            this.genreTaker.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.genreTaker.SelectedText = "";
            this.genreTaker.SelectionLength = 0;
            this.genreTaker.SelectionStart = 0;
            this.genreTaker.ShortcutsEnabled = true;
            this.genreTaker.Size = new System.Drawing.Size(347, 46);
            this.genreTaker.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.genreTaker.TabIndex = 11;
            this.genreTaker.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.genreTaker.TextMarginBottom = 0;
            this.genreTaker.TextMarginLeft = 3;
            this.genreTaker.TextMarginTop = 0;
            this.genreTaker.TextPlaceholder = "Genre";
            this.genreTaker.UseSystemPasswordChar = false;
            this.genreTaker.WordWrap = true;
            // 
            // nameTaker
            // 
            this.nameTaker.AcceptsReturn = false;
            this.nameTaker.AcceptsTab = false;
            this.nameTaker.AnimationSpeed = 200;
            this.nameTaker.AutoCompleteMode = System.Windows.Forms.AutoCompleteMode.None;
            this.nameTaker.AutoCompleteSource = System.Windows.Forms.AutoCompleteSource.None;
            this.nameTaker.BackColor = System.Drawing.Color.White;
            this.nameTaker.BackgroundImage = ((System.Drawing.Image)(resources.GetObject("nameTaker.BackgroundImage")));
            this.nameTaker.BorderColorActive = System.Drawing.Color.DodgerBlue;
            this.nameTaker.BorderColorDisabled = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            this.nameTaker.BorderColorHover = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            this.nameTaker.BorderColorIdle = System.Drawing.Color.Silver;
            this.nameTaker.BorderRadius = 1;
            this.nameTaker.BorderThickness = 1;
            this.nameTaker.CharacterCasing = System.Windows.Forms.CharacterCasing.Normal;
            this.nameTaker.Cursor = System.Windows.Forms.Cursors.IBeam;
            this.nameTaker.DefaultFont = new System.Drawing.Font("Segoe UI", 9.25F);
            this.nameTaker.DefaultText = "";
            this.nameTaker.FillColor = System.Drawing.Color.White;
            this.nameTaker.HideSelection = true;
            this.nameTaker.IconLeft = null;
            this.nameTaker.IconLeftCursor = System.Windows.Forms.Cursors.IBeam;
            this.nameTaker.IconPadding = 10;
            this.nameTaker.IconRight = null;
            this.nameTaker.IconRightCursor = System.Windows.Forms.Cursors.IBeam;
            this.nameTaker.Lines = new string[0];
            this.nameTaker.Location = new System.Drawing.Point(83, 190);
            this.nameTaker.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.nameTaker.MaxLength = 32767;
            this.nameTaker.MinimumSize = new System.Drawing.Size(1, 1);
            this.nameTaker.Modified = false;
            this.nameTaker.Multiline = false;
            this.nameTaker.Name = "nameTaker";
            stateProperties69.BorderColor = System.Drawing.Color.DodgerBlue;
            stateProperties69.FillColor = System.Drawing.Color.Empty;
            stateProperties69.ForeColor = System.Drawing.Color.Empty;
            stateProperties69.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nameTaker.OnActiveState = stateProperties69;
            stateProperties70.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(204)))), ((int)(((byte)(204)))), ((int)(((byte)(204)))));
            stateProperties70.FillColor = System.Drawing.Color.FromArgb(((int)(((byte)(240)))), ((int)(((byte)(240)))), ((int)(((byte)(240)))));
            stateProperties70.ForeColor = System.Drawing.Color.FromArgb(((int)(((byte)(109)))), ((int)(((byte)(109)))), ((int)(((byte)(109)))));
            stateProperties70.PlaceholderForeColor = System.Drawing.Color.DarkGray;
            this.nameTaker.OnDisabledState = stateProperties70;
            stateProperties71.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(105)))), ((int)(((byte)(181)))), ((int)(((byte)(255)))));
            stateProperties71.FillColor = System.Drawing.Color.Empty;
            stateProperties71.ForeColor = System.Drawing.Color.Empty;
            stateProperties71.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nameTaker.OnHoverState = stateProperties71;
            stateProperties72.BorderColor = System.Drawing.Color.Silver;
            stateProperties72.FillColor = System.Drawing.Color.White;
            stateProperties72.ForeColor = System.Drawing.Color.Empty;
            stateProperties72.PlaceholderForeColor = System.Drawing.Color.Empty;
            this.nameTaker.OnIdleState = stateProperties72;
            this.nameTaker.Padding = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.nameTaker.PasswordChar = '\0';
            this.nameTaker.PlaceholderForeColor = System.Drawing.Color.Silver;
            this.nameTaker.PlaceholderText = "Book name";
            this.nameTaker.ReadOnly = false;
            this.nameTaker.ScrollBars = System.Windows.Forms.ScrollBars.None;
            this.nameTaker.SelectedText = "";
            this.nameTaker.SelectionLength = 0;
            this.nameTaker.SelectionStart = 0;
            this.nameTaker.ShortcutsEnabled = true;
            this.nameTaker.Size = new System.Drawing.Size(347, 46);
            this.nameTaker.Style = Bunifu.UI.WinForms.BunifuTextBox._Style.Material;
            this.nameTaker.TabIndex = 9;
            this.nameTaker.TextAlign = System.Windows.Forms.HorizontalAlignment.Left;
            this.nameTaker.TextMarginBottom = 0;
            this.nameTaker.TextMarginLeft = 3;
            this.nameTaker.TextMarginTop = 0;
            this.nameTaker.TextPlaceholder = "Book name";
            this.nameTaker.UseSystemPasswordChar = false;
            this.nameTaker.WordWrap = true;
            // 
            // ModifyBookScreen
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(8F, 16F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.BackColor = System.Drawing.Color.Linen;
            this.ClientSize = new System.Drawing.Size(993, 581);
            this.Controls.Add(this.priceTaker);
            this.Controls.Add(this.topPanel);
            this.Controls.Add(this.saveBt);
            this.Controls.Add(this.statusTaker);
            this.Controls.Add(this.amountTaker);
            this.Controls.Add(this.publisherTaker);
            this.Controls.Add(this.publishYearTaker);
            this.Controls.Add(this.posTaker);
            this.Controls.Add(this.authorTaker);
            this.Controls.Add(this.genreTaker);
            this.Controls.Add(this.nameTaker);
            this.FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            this.Margin = new System.Windows.Forms.Padding(4, 4, 4, 4);
            this.Name = "ModifyBookScreen";
            this.Text = "ModifyBookScreen";
            this.topPanel.ResumeLayout(false);
            this.topPanel.PerformLayout();
            this.ResumeLayout(false);

        }

        #endregion

        private Bunifu.UI.WinForms.BunifuTextBox priceTaker;
        private System.Windows.Forms.Panel topPanel;
        private Bunifu.UI.WinForms.BunifuImageButton exitButton;
        private System.Windows.Forms.Label label1;
        private Bunifu.Framework.UI.BunifuDragControl bunifuDragControl1;
        private Bunifu.UI.WinForms.BunifuButton.BunifuButton saveBt;
        private Bunifu.UI.WinForms.BunifuTextBox statusTaker;
        private Bunifu.UI.WinForms.BunifuTextBox amountTaker;
        private Bunifu.UI.WinForms.BunifuTextBox publisherTaker;
        private Bunifu.UI.WinForms.BunifuTextBox publishYearTaker;
        private Bunifu.UI.WinForms.BunifuTextBox posTaker;
        private Bunifu.UI.WinForms.BunifuTextBox authorTaker;
        private Bunifu.UI.WinForms.BunifuTextBox genreTaker;
        private Bunifu.UI.WinForms.BunifuTextBox nameTaker;
    }
}